Repository google/kf, pull requests merged in 2019-05, with the labels that each got.

#4 pkg/kf/fakes: adds copyright to fake_istio_client
  pkg/kf/fake/fake_istio_client.go
Labels: bug

#2 Adds doctor command to kf
  pkg/kf/commands/doctor/doctor.go
  pkg/kf/commands/doctor/doctor_test.go
  pkg/kf/commands/root.go
  pkg/kf/doctor/cluster.go
  pkg/kf/doctor/diagnostic.go
  pkg/kf/doctor/diagnostic_test.go
  pkg/kf/internal/testutil/assertions.go
Labels: enhancement

#5 Fixed VCAP_SERVICES
  pkg/kf/service-bindings/client.go
  pkg/kf/service-bindings/client_test.go
  pkg/kf/service-bindings/vcap.go
  pkg/kf/service-bindings/vcap_test.go
Labels: bug

#3 Adds sample buildpacks and install instructions
  README.md
  buildpack-samples/README.md
  buildpack-samples/builder.toml
  buildpack-samples/go-buildpack/README.md
  buildpack-samples/go-buildpack/bin/build
  buildpack-samples/go-buildpack/bin/detect
  buildpack-samples/go-buildpack/buildpack.toml
  buildpack-samples/gradle-buildpack/README.md
  buildpack-samples/gradle-buildpack/bin/build
  buildpack-samples/gradle-buildpack/bin/detect
  buildpack-samples/gradle-buildpack/buildpack.toml
  buildpack-samples/hello-world-buildpack/README.md
  buildpack-samples/hello-world-buildpack/bin/build
  buildpack-samples/hello-world-buildpack/bin/detect
  buildpack-samples/hello-world-buildpack/buildpack.toml
  buildpack-samples/java-buildpack/README.md
  buildpack-samples/java-buildpack/bin/build
  buildpack-samples/java-buildpack/bin/detect
  buildpack-samples/java-buildpack/buildpack.toml
  buildpack-samples/nodejs-buildpack/README.md
  buildpack-samples/nodejs-buildpack/bin/build
  buildpack-samples/nodejs-buildpack/bin/detect
  buildpack-samples/nodejs-buildpack/buildpack.toml
  docs/install.md
  install.md
  third_party/gcp-service-broker/Chart.yaml
  third_party/gcp-service-broker/README.md
  third_party/gcp-service-broker/cf-tutorial.md
  third_party/gcp-service-broker/charts/mysql-0.15.0.tgz
  third_party/gcp-service-broker/gcp-service-broker-5.0.0.tgz
  third_party/gcp-service-broker/requirements.lock
  third_party/gcp-service-broker/requirements.yaml
  third_party/gcp-service-broker/values.yaml
Labels: docs

#30 fixes and simplifies install instructions using mini-broker
  docs/install.md
Labels: docs, install

#38 Inject VCAP environment variables on push
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/environment_client.go
  pkg/kf/fake/fake_systemenvinjector.go
  pkg/kf/fake/interfaces.go
  pkg/kf/internal/cfutil/doc.go
  pkg/kf/internal/cfutil/vcapapp.go
  pkg/kf/internal/cfutil/vcapapp_test.go
  pkg/kf/internal/envutil/envutil.go
  pkg/kf/internal/envutil/envutil_test.go
  pkg/kf/push.go
  pkg/kf/push_test.go
  pkg/kf/systemenvinjector.go
  pkg/kf/systemenvinjector_test.go
Labels: enhancement, mvp

#70 created client generator
  pkg/kf/internal/tools/clientgen/client.go
  pkg/kf/internal/tools/clientgen/common-options.yml
  pkg/kf/internal/tools/clientgen/genclient.go
  pkg/kf/internal/tools/clientgen/gentest/client.go
  pkg/kf/internal/tools/clientgen/gentest/client.yml
  pkg/kf/internal/tools/clientgen/gentest/client_test.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.clientoptions.go
  pkg/kf/internal/tools/clientgen/tmplclient.go
  pkg/kf/internal/tools/clientgen/tmplfunctional.go
  pkg/kf/internal/tools/clientgen/tmplheader.go
  pkg/kf/internal/tools/option-builder/option-builder.go
Labels: enhancement

#74 added spaces
  docs/spec/README.md
  docs/spec/TEMPLATE.md
  docs/spec/space.md
  pkg/kf/commands/root.go
  pkg/kf/commands/spaces/create.go
  pkg/kf/commands/spaces/create_test.go
  pkg/kf/commands/spaces/delete.go
  pkg/kf/commands/spaces/delete_test.go
  pkg/kf/commands/spaces/doc.go
  pkg/kf/commands/spaces/list.go
  pkg/kf/commands/spaces/list_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/spaces/client.go
  pkg/kf/spaces/client.yml
  pkg/kf/spaces/doc.go
  pkg/kf/spaces/fake/fake_client.go
  pkg/kf/spaces/fake/interfaces.go
  pkg/kf/spaces/kfspace.go
  pkg/kf/spaces/kfspace_test.go
  pkg/kf/spaces/zz_generated.client.go
  pkg/kf/spaces/zz_generated.clientoptions.go
Labels: enhancement

#86 removed need for config listing
  pkg/kf/commands/apps/apps.go
  pkg/kf/commands/apps/apps_test.go
  pkg/kf/deploy.go
  pkg/kf/fake/fake_lister.go
  pkg/kf/list.go
  pkg/kf/list_test.go
  pkg/kf/options.go
  pkg/kf/options.yml
Labels: cla: yes, enhancement

#88 initial addition of apps client
  pkg/kf/apps/client.go
  pkg/kf/apps/client.yml
  pkg/kf/apps/doc.go
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/apps/fake/interfaces.go
  pkg/kf/apps/kfapp.go
  pkg/kf/apps/kfapp_test.go
  pkg/kf/apps/zz_generated.client.go
  pkg/kf/apps/zz_generated.clientoptions.go
  pkg/kf/commands/apps/delete.go
  pkg/kf/commands/apps/delete_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/delete.go
  pkg/kf/delete_test.go
  pkg/kf/fake/fake_deleter.go
  pkg/kf/fake/interfaces.go
  pkg/kf/options.go
  pkg/kf/options.yml
Labels: cla: yes

#92 doc spec rewording
  docs/spec/README.md
Labels: cla: yes

#94 pkg/kf/buildpacks: upload buildpacks cluster wide
  pkg/kf/buildpacks/build_template_uploader.go
  pkg/kf/buildpacks/build_template_uploader_test.go
  pkg/kf/buildpacks/buildpack_lister.go
  pkg/kf/buildpacks/buildpack_lister_test.go
  pkg/kf/buildpacks/fake/fake_build_template_uploader.go
  pkg/kf/buildpacks/fake/fake_buildpack_lister.go
  pkg/kf/buildpacks/options.go
  pkg/kf/buildpacks/options.yml
  pkg/kf/builds/util.go
  pkg/kf/commands/buildpacks/buildpacks.go
  pkg/kf/commands/buildpacks/buildpacks_test.go
  pkg/kf/commands/buildpacks/upload_buildpacks.go
  pkg/kf/commands/buildpacks/upload_buildpacks_test.go
  pkg/kf/push.go
  pkg/kf/push_test.go
Labels: cla: yes

#100 moved proxy to using apps client
  pkg/kf/commands/apps/proxy.go
  pkg/kf/commands/apps/proxy_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
Labels: cla: yes

#97 pkg/kf/commands/apps: adds buildpack integration test
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/testutil/integration.go
Labels: cla: yes

#102 fixed #46
  pkg/kf/commands/apps/proxy.go
Labels: bug, cla: yes

#101 Moved env commands to use apps client
  pkg/kf/apps/kfapp.go
  pkg/kf/apps/kfapp_test.go
  pkg/kf/commands/apps/env.go
  pkg/kf/commands/apps/env_test.go
  pkg/kf/commands/apps/set_env.go
  pkg/kf/commands/apps/set_env_test.go
  pkg/kf/commands/apps/unset_env.go
  pkg/kf/commands/apps/unset_env_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/deploy_test.go
  pkg/kf/environment_client.go
  pkg/kf/environment_client_test.go
  pkg/kf/fake/fake_environment_client.go
  pkg/kf/fake/interfaces.go
Labels: cla: yes

#103 Moved app listing to use the apps client.
  pkg/kf/commands/apps/apps.go
  pkg/kf/commands/apps/apps_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
Labels: cla: yes, cleanup

#104 pkg/kf/buildpacks: merge into Client
  pkg/kf/buildpacks/builder_creator.go
  pkg/kf/buildpacks/builder_creator_test.go
  pkg/kf/buildpacks/buildpack_lister.go
  pkg/kf/buildpacks/buildpack_lister_test.go
  pkg/kf/buildpacks/client.go
  pkg/kf/buildpacks/client_test.go
  pkg/kf/buildpacks/fake/fake_build_template_uploader.go
  pkg/kf/buildpacks/fake/fake_builder_creator.go
  pkg/kf/buildpacks/fake/fake_buildpack_lister.go
  pkg/kf/buildpacks/fake/fake_client.go
  pkg/kf/buildpacks/fake/interfaces.go
  pkg/kf/commands/buildpacks/buildpacks.go
  pkg/kf/commands/buildpacks/buildpacks_test.go
  pkg/kf/commands/buildpacks/upload_buildpacks.go
  pkg/kf/commands/buildpacks/upload_buildpacks_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
Labels: cla: yes, cleanup

#108 pkg/kf: renames LogTailer.Tail to DeployLogs
  pkg/kf/fake/fake_log_tailer.go
  pkg/kf/log_tailer.go
  pkg/kf/log_tailer_test.go
  pkg/kf/push.go
  pkg/kf/push_test.go
Labels: cla: yes, cleanup

#107 adds "completion" command for bash auto-complete
  pkg/kf/commands/root.go
Labels: cla: yes

#112 remove accidentally committed test file
  scripts/wow.sh
Labels: cla: yes

#113 hack: renames scripts dir to hack
  .travis.yml
  hack/README.md
  hack/build.sh
  hack/check-go-fmt.sh
  hack/check-go-generate.sh
  hack/clean-integration-tests.sh
  hack/test.sh
  hack/unit-test.sh
  hack/update-codegen.sh
Labels: cla: yes

#105 pkg/kf/buildpacks: Client implements doctor.Diagnosable
  pkg/kf/buildpacks/client.go
  pkg/kf/buildpacks/fake/fake_client.go
  pkg/kf/commands/root.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
Labels: cla: yes

#115 Moved SystemEnvInjector to a sub-package.
  pkg/kf/apps/client.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/deploy.go
  pkg/kf/deploy_test.go
  pkg/kf/fake/interfaces.go
  pkg/kf/systemenvinjector/fake/fake_systemenvinjector.go
  pkg/kf/systemenvinjector/fake/interfaces.go
  pkg/kf/systemenvinjector/systemenvinjector.go
  pkg/kf/systemenvinjector/systemenvinjector_test.go
Labels: cla: yes, cleanup

#116 hack: run more linters and vetters
  .travis.yml
  hack/README.md
  hack/check-linters.sh
  install.md
  pkg/kf/buildpacks/client.go
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/generator/registrar.go
  pkg/kf/internal/envutil/envutil_test.go
  pkg/kf/internal/tools/generator/gen.go
  pkg/kf/istio_client_test.go
  pkg/kf/list_test.go
  pkg/kf/manifest/manifest_test.go
  pkg/kf/push.go
  pkg/kf/service-bindings/client_test.go
  pkg/kf/systemenvinjector/systemenvinjector.go
  pkg/kf/testutil/integration.go
Labels: cla: yes

#118 Added the ability to upsert values.
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/apps/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/gentest/client_test.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/tmplclient.go
  pkg/kf/spaces/fake/fake_client.go
  pkg/kf/spaces/zz_generated.client.go
Labels: cla: yes, enhancement
