Repository google/kf, pull requests merged in 2019-11, with the labels that each got.

#837 hack: adds create-gke-secret.sh
  ci/concourse/pipelines/pr-unipipeline.yml
  hack/README.md
  hack/create-gke-secret.sh
Labels: cla: yes, ok-to-test

#840 hack: fix create-gke-secret
  hack/create-gke-secret.sh
Labels: cla: yes

#842 hack: update create-gke-secret.sh push secret name
  hack/create-gke-secret.sh
Labels: cla: yes

#845 Update pr pipeline to always destroy terraform first
  ci/concourse/pipelines/pr-unipipeline.yml
Labels: cla: yes, ok-to-test

#841 updated push event watcher
  pkg/kf/apps/log_tailer.go
  pkg/kf/apps/log_tailer_test.go
Labels: cla: yes, ok-to-test

#847 add new kingpin to exclude
  go.mod
  hack/check-code-generator.sh
Labels: cla: yes, ok-to-test

#848 Concourse: don't wait for Terraform destroy
  ci/concourse/pipelines/pr-unipipeline.yml
Labels: cla: yes, ok-to-test

#767 Synchronous Service Brokers
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-service-broker.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-service-broker.md
  pkg/kf/commands/service-bindings/integration_test.go
  pkg/kf/commands/service-brokers/create-service-broker.go
  pkg/kf/commands/service-brokers/create-service-broker_test.go
  pkg/kf/commands/service-brokers/delete-service-broker.go
  pkg/kf/commands/service-brokers/delete-service-broker_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/service-brokers/cluster/client.go
  pkg/kf/service-brokers/cluster/client.yml
  pkg/kf/service-brokers/cluster/doc.go
  pkg/kf/service-brokers/cluster/fake/fake_client.go
  pkg/kf/service-brokers/cluster/fake/interfaces.go
  pkg/kf/service-brokers/cluster/zz_generated.client.go
  pkg/kf/service-brokers/cluster/zz_generated.clientoptions.go
  pkg/kf/service-brokers/namespaced/client.go
  pkg/kf/service-brokers/namespaced/client.yml
  pkg/kf/service-brokers/namespaced/doc.go
  pkg/kf/service-brokers/namespaced/fake/fake_client.go
  pkg/kf/service-brokers/namespaced/fake/interfaces.go
  pkg/kf/service-brokers/namespaced/zz_generated.client.go
  pkg/kf/service-brokers/namespaced/zz_generated.clientoptions.go
Labels: cla: yes, ok-to-test

#846 Document UAA CloudSQL installation with Terraform config
  docs/apps/uaa/.gitignore
  docs/apps/uaa/cloudsql-deployment.md
  docs/apps/uaa/cloudsql.tf
  docs/apps/uaa/main.tf
  docs/apps/uaa/output.tf
  docs/apps/uaa/secrets.tf
  docs/apps/uaa/terraform.tfvars
  docs/apps/uaa/vars.tf
  third_party/VENDOR-LICENSE
Labels: cla: yes

#853 update knative build version to v0.7.0
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/pr-unipipeline.yml
  ci/concourse/pipelines/release-pipeline.yml
  docs/install.md
  pkg/kf/commands/install/kf/kf.go
Labels: cla: yes

#827 pkg/reconciler: copy secrets from kf namespace
  config/.gitignore
  config/config-secrets-example.yaml
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/apis/kf/v1alpha1/alg_types.go
  pkg/apis/kf/v1alpha1/space_defaults.go
  pkg/apis/kf/v1alpha1/space_defaults_test.go
  pkg/apis/kf/v1alpha1/space_lifecycle.go
  pkg/apis/kf/v1alpha1/space_lifecycle_test.go
  pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/app/reconciler.go
  pkg/reconciler/base.go
  pkg/reconciler/source/config/secrets.go
  pkg/reconciler/source/config/secrets_test.go
  pkg/reconciler/source/config/store.go
  pkg/reconciler/source/config/store_test.go
  pkg/reconciler/source/config/testdata/config-secrets.yaml
  pkg/reconciler/source/resources/build.go
  pkg/reconciler/source/resources/build_test.go
  pkg/reconciler/space/controller.go
  pkg/reconciler/space/reconciler.go
  pkg/reconciler/space/resources/build_service_account.go
  pkg/reconciler/space/resources/build_service_account_test.go
Labels: cla: yes, ok-to-test

#857 turn on go111module
  hack/update-codegen.sh
Labels: cla: yes

#859 ci/concourse/pipelines: use PR's hack dir
  ci/concourse/pipelines/pr-unipipeline.yml
Labels: cla: yes

#860 ci/concourse/pipelines: install both Tekton and Knative Build
  ci/concourse/pipelines/pr-unipipeline.yml
Labels: cla: yes

#852 change pipeline to try terraform destroy
  ci/concourse/pipelines/pr-unipipeline.yml
Labels: cla: yes

#862 Add reap concourse step
  ci/concourse/pipelines/pr-unipipeline.yml
Labels: cla: yes

#865 fix listen failing unit tests
  pkg/kf/commands/apps/proxy.go
  pkg/kf/commands/routes/proxy_route.go
  pkg/kf/internal/utils/cli/utils.go
Labels: cla: yes, ok-to-test

#863 Fix/custom network
  ci/concourse/pipelines/pr-unipipeline.yml
  ci/concourse/terraform/main.tf
  hack/terraform-pre-destroy.sh
Labels: cla: yes, ok-to-test

#861 Bump service catalog memory requirements
  third_party/service-catalog/manifests/catalog/templates/apiserver-deployment.yaml
  third_party/service-catalog/values/catalog.yml
Labels: cla: yes, ok-to-test

#868 pkg/kf/commands/install/gke: upgrade GKE version
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/pr-unipipeline.yml
  ci/concourse/pipelines/release-pipeline.yml
  pkg/kf/commands/install/gke/gke.go
Labels: bug, cla: yes, ok-to-test

#867 Fix error in terraform-pre-destroy.sh
  ci/concourse/pipelines/pr-unipipeline.yml
  hack/terraform-pre-destroy.sh
Labels: cla: yes, ok-to-test

#870 fix terraform in ci
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/pr-unipipeline.yml
  ci/concourse/pipelines/release-pipeline.yml
  ci/concourse/terraform/main.tf
Labels: cla: yes, ok-to-test

#804 Introduce black box testing
  pkg/kf/testutil/integration.go
  pkg/reconciler/integration/README.md
  pkg/reconciler/integration/defaults_test.go
  pkg/reconciler/integration/doc.go
  pkg/reconciler/integration/testdata/defaults/README.md
  pkg/reconciler/integration/testdata/defaults/serving_v1alpha1.yaml
Labels: cla: yes, enhancement, ok-to-test

#811 Add support for routing configmap
  config/config-routing.yaml
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/routes/integration_test.go
  pkg/reconciler/base.go
  pkg/reconciler/route/config/routing.go
  pkg/reconciler/route/config/store.go
  pkg/reconciler/route/config/store_test.go
  pkg/reconciler/route/config/testdata/config-routing.yaml
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/default_config_logger.go
  pkg/reconciler/route/reconciler.go
  pkg/reconciler/route/reconciler_test.go
  pkg/reconciler/route/resources/virtual_service.go
  pkg/reconciler/route/resources/virtual_service_test.go
Labels: cla: yes, ok-to-test

#864 Move virtualservices to same namespace as routeclaims
  pkg/apis/kf/v1alpha1/utils.go
  pkg/kf/commands/service-bindings/integration_test.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/controller_test.go
  pkg/reconciler/route/reconciler.go
  pkg/reconciler/route/reconciler_test.go
  pkg/reconciler/route/resources/virtual_service.go
  pkg/reconciler/route/resources/virtual_service_test.go
Labels: cla: yes, ok-to-test

#854 allow kubectl apps to show similar output to kf apps
  config/300-app.yaml
  pkg/apis/kf/v1alpha1/app_lifecycle.go
  pkg/apis/kf/v1alpha1/app_types.go
  pkg/apis/kf/v1alpha1/app_types_test.go
  pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/app/reconciler.go
Labels: cla: yes, ok-to-test

#875 third_party/service-catalog: fix README.md
  third_party/service-catalog/README.md
  third_party/service-catalog/values/catalog.yaml
Labels: cla: yes

#872 Feature/cache push
  hack/integration-test.sh
  hack/unit-test.sh
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/routes/integration_test.go
  pkg/kf/commands/service-bindings/integration_test.go
  pkg/kf/testutil/integration.go
Labels: cla: yes, ok-to-test

#856 pull env from image for uid/gid
  cmd/setup-buildpack-build/main.go
  config/300-buildpack-clusterbuildtemplate.yaml
Labels: cla: yes, ok-to-test

#871 doctor for mutating webhook
  pkg/kf/doctor/cluster.go
Labels: cla: yes, enhancement, ok-to-test

#881 updated stackdriver config
  ci/concourse/terraform/main.tf
Labels: cla: yes, ok-to-test

#880 finish removing async commands. Fixes #599
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-space.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_unbind-service.md
  pkg/kf/commands/apps/delete.go
  pkg/kf/commands/routes/create_route.go
  pkg/kf/commands/routes/delete_route.go
  pkg/kf/commands/service-bindings/unbind-service.go
  pkg/kf/commands/service-bindings/unbind-service_test.go
  pkg/kf/commands/spaces/delete.go
  pkg/kf/internal/utils/cli/utils.go
Labels: cla: yes, ok-to-test

#889 ci/concourse/pipelines: fix nightly pipelines
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/pr-unipipeline.yml
Labels: cla: yes

#887 config: explicitly state input types as strings
  config/300-buildpack-clustertask.yaml
  config/300-kaniko-clustertask.yaml
Labels: cla: yes, ok-to-test

#891 Use Terraform for Service Accounts and Subnetworks
  ci/concourse/pipelines/pr-unipipeline.yml
  ci/concourse/terraform/main.tf
  hack/create-gke-secret.sh
Labels: cla: yes, ok-to-test

#892 init container for kf controller
  cmd/controller-init/main.go
  config/200-clusterrole.yaml
  config/controller.yaml
Labels: cla: yes, ok-to-test

#895 pkg/kf/commands/install/gke: fail when cluster fails to create
  pkg/kf/commands/install/gke/gke.go
Labels: cla: yes

#897 moved to release channels on GKE
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/pr-unipipeline.yml
  ci/concourse/pipelines/release-pipeline.yml
  ci/concourse/terraform/main.tf
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_install_gke.md
  pkg/kf/cli/prompts.go
  pkg/kf/commands/install/gke/gke.go
Labels: cla: yes, ok-to-test

#899 Feature/cloud build
  .travis.yml
  README.md
  ci/cloudbuild/unit.yaml
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/pr-unipipeline.yml
  ci/concourse/pipelines/release-pipeline.yml
  hack/setup-gitignore.sh
Labels: cla: yes

#896 cmd/controller-init: add config-secrets if not present
  cmd/controller-init/main.go
Labels: cla: yes, ok-to-test

#900 hack: fix variable name in create-gke-secret
  hack/create-gke-secret.sh
Labels: bug, cla: yes
