Repository google/kf, pull requests merged in 2019-07, with the labels that each got.

#123 Support setting scale bounds
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/manifest/manifest.go
  pkg/kf/options.go
  pkg/kf/options.yml
  pkg/kf/push.go
Labels: cla: yes, enhancement

#242 support loading kubeconfig from env
  pkg/kf/commands/config/config.go
Labels: cla: yes

#247 use client-go's home rather than Hashicorp's
  pkg/kf/commands/config/config.go
  pkg/kf/commands/config/config_test.go
Labels: cla: yes, cleanup

#248 added space command
  pkg/kf/commands/root.go
  pkg/kf/commands/spaces/get.go
  pkg/kf/commands/spaces/get_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
Labels: cla: yes, enhancement

#244 Feature/webhook
  cmd/webhook/main.go
  config/400-webhook-service.yaml
  config/config-defaults.yaml
  config/webhook.yaml
  go.mod
  go.sum
  pkg/apis/kf/v1alpha1/space_validation.go
  pkg/apis/kf/v1alpha1/space_validation_test.go
Labels: cla: yes, enhancement

#258 added app validation webhook and basic validation
  cmd/webhook/main.go
  pkg/apis/kf/v1alpha1/app_types.go
  pkg/apis/kf/v1alpha1/app_types_test.go
  pkg/apis/kf/v1alpha1/app_validation.go
  pkg/apis/kf/v1alpha1/app_validation_test.go
Labels: cla: yes, enhancement

#260 Update README.md with slack badge
  README.md
Labels: cla: yes

#256 gomod: remove duplicates poy/kontext
  go.sum
Labels: cla: yes

#262 added additional printer columns to routes
  config/300-route.yaml
Labels: cla: yes, enhancement

#252 ResourceQuota and LimitRange updates in Space reconciliation
  config/200-clusterrole.yaml
  pkg/apis/kf/v1alpha1/space_lifecycle.go
  pkg/apis/kf/v1alpha1/space_lifecycle_test.go
  pkg/apis/kf/v1alpha1/space_types.go
  pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
  pkg/client/injection/informers/kubernetes/limitrange/fake/fake.go
  pkg/client/injection/informers/kubernetes/limitrange/limitrange.go
  pkg/client/injection/informers/kubernetes/resourcequota/fake/fake.go
  pkg/client/injection/informers/kubernetes/resourcequota/resourcequota.go
  pkg/reconciler/space/controller.go
  pkg/reconciler/space/reconciler.go
  pkg/reconciler/space/resources/limitrange.go
  pkg/reconciler/space/resources/limitrange_test.go
  pkg/reconciler/space/resources/resourcequota.go
  pkg/reconciler/space/resources/resourcequota_test.go
Labels: cla: yes

#269 Add Env vars to Buildpack Builds
  pkg/apis/kf/v1alpha1/source_types.go
  pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/source/resources/build.go
  pkg/reconciler/source/resources/build_test.go
Labels: cla: yes

#270 Source validation
  pkg/apis/kf/v1alpha1/source_types.go
  pkg/apis/kf/v1alpha1/source_validation.go
  pkg/apis/kf/v1alpha1/source_validation_test.go
  pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
Labels: cla: yes

#267 Making registry settings more generic.
  docs/install.md
  hack/upload-buildpacks-stack.sh
  hack/upload-buildpacks.sh
Labels: cla: yes

#277 added commands to manipulate space env vars
  pkg/kf/commands/root.go
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/config_space_test.go
  pkg/kf/commands/spaces/get.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
Labels: cla: yes, enhancement

#280 fix proxy command
  pkg/kf/commands/apps/proxy.go
Labels: cla: yes

#281 added ability to set buildpack builder image
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/config_space_test.go
Labels: cla: yes

#288 go mod tidy
  go.sum
Labels: cla: yes

#300 Use kf-releases buildpack builder in config
  config/300-buildpack-clusterbuildtemplate.yaml
Labels: cla: yes

#298 space defaulting and validation
  pkg/apis/kf/v1alpha1/space_defaults.go
  pkg/apis/kf/v1alpha1/space_defaults_test.go
  pkg/apis/kf/v1alpha1/space_types.go
  pkg/apis/kf/v1alpha1/space_validation.go
  pkg/apis/kf/v1alpha1/space_validation_test.go
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/config_space_test.go
  pkg/kf/commands/spaces/create.go
  pkg/kf/commands/spaces/get.go
  pkg/kf/spaces/kfspace.go
  pkg/kf/spaces/kfspace_test.go
Labels: cla: yes

#299 cmd/webhook: adds validation for v1alpha1.Route
  cmd/webhook/main.go
  pkg/apis/kf/v1alpha1/route_validation.go
  pkg/apis/kf/v1alpha1/route_validation_test.go
  pkg/apis/kf/v1alpha1/utils.go
  pkg/apis/kf/v1alpha1/utils_test.go
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/routes/create_route.go
  pkg/kf/commands/routes/create_route_test.go
  pkg/kf/commands/routes/delete_route.go
  pkg/kf/commands/routes/delete_route_test.go
  pkg/kf/commands/routes/integration_test.go
  pkg/kf/commands/routes/map_route.go
  pkg/kf/commands/routes/map_route_test.go
  pkg/kf/commands/routes/unmap_route.go
  pkg/kf/commands/routes/unmap_route_test.go
  pkg/kf/testutil/integration.go
  pkg/reconciler/route/reconciler.go
  pkg/reconciler/route/resources/virtual_service.go
  pkg/reconciler/route/resources/virtual_service_test.go
Labels: cla: yes

#301 kf/builds: provide env vars to build steps
  pkg/kf/builds/builtins.go
  pkg/kf/builds/options.go
  pkg/kf/builds/options.yml
  pkg/kf/builds/util.go
  pkg/kf/builds/util_test.go
  pkg/kf/push.go
Labels: cla: yes

#302 ci/concourse: adds job to create nightly builds
  ci/concourse/pipelines/kf-pipeline.yml
  docs/install.md
  docs/install/Kf-with-CloudRun-on-GKE.md
  hack/upload-release.sh
Labels: cla: yes

#303 infrastructure: removes infrastructure directory
  infrastructure/.gitignore
  infrastructure/deploy_knative.sh
  infrastructure/gke.tf
  infrastructure/knative.tf
  infrastructure/vars.tf
Labels: cla: yes

#304 removes sample buildpacks
  hack/upload-buildpacks-stack.sh
  hack/upload-buildpacks.sh
  samples/buildpacks/builder/README.md
  samples/buildpacks/builder/builder.toml
  samples/buildpacks/builder/go-buildpack/README.md
  samples/buildpacks/builder/go-buildpack/bin/build
  samples/buildpacks/builder/go-buildpack/bin/detect
  samples/buildpacks/builder/go-buildpack/buildpack.toml
  samples/buildpacks/builder/gradle-buildpack/README.md
  samples/buildpacks/builder/gradle-buildpack/bin/build
  samples/buildpacks/builder/gradle-buildpack/bin/detect
  samples/buildpacks/builder/gradle-buildpack/buildpack.toml
  samples/buildpacks/builder/java-buildpack/README.md
  samples/buildpacks/builder/java-buildpack/bin/build
  samples/buildpacks/builder/java-buildpack/bin/detect
  samples/buildpacks/builder/java-buildpack/buildpack.toml
  samples/buildpacks/builder/nodejs-buildpack/README.md
  samples/buildpacks/builder/nodejs-buildpack/bin/build
  samples/buildpacks/builder/nodejs-buildpack/bin/detect
  samples/buildpacks/builder/nodejs-buildpack/buildpack.toml
  samples/buildpacks/stacks/bionic/base/Dockerfile
  samples/buildpacks/stacks/bionic/build/Dockerfile
  samples/buildpacks/stacks/bionic/run/Dockerfile
Labels: cla: yes

#307 patches to app lifecycle
  pkg/apis/kf/v1alpha1/app_lifecycle.go
  pkg/apis/kf/v1alpha1/app_types.go
  pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/app/reconciler.go
Labels: cla: yes

#310 hack: remove any usage of `realpath`
  hack/build.sh
  hack/codegen-packages.txt
  hack/setup-codegen.sh
  hack/update-codegen.sh
Labels: cla: yes

#311 Feature/push uses space
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/apps/testdata/example-app/manifest.yml
  pkg/kf/commands/config/config.go
  pkg/kf/commands/config/config_test.go
Labels: cla: yes

#308 pkg/kf/commands/apps: adds scale command
  pkg/apis/kf/v1alpha1/app_validation.go
  pkg/kf/commands/apps/scale.go
  pkg/kf/commands/apps/scale_test.go
  pkg/kf/commands/root.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/kfapps/client.go
  pkg/kf/kfapps/client.yml
  pkg/kf/kfapps/doc.go
  pkg/kf/kfapps/fake/fake_client.go
  pkg/kf/kfapps/fake/interfaces.go
  pkg/kf/kfapps/zz_generated.client.go
  pkg/kf/kfapps/zz_generated.clientoptions.go
Labels: cla: yes

#312 add build name to source status
  pkg/apis/kf/v1alpha1/source_lifecycle.go
  pkg/apis/kf/v1alpha1/source_lifecycle_test.go
  pkg/apis/kf/v1alpha1/source_types.go
Labels: bug, cla: yes

#316 added sources client
  pkg/kf/commands/builds/list.go
  pkg/kf/commands/builds/list_test.go
  pkg/kf/commands/builds/logs.go
  pkg/kf/commands/builds/logs_test.go
  pkg/kf/commands/root.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/sources/client.go
  pkg/kf/sources/client.yml
  pkg/kf/sources/doc.go
  pkg/kf/sources/fake/fake_client.go
  pkg/kf/sources/fake/interfaces.go
  pkg/kf/sources/kfsource.go
  pkg/kf/sources/kfsource_test.go
  pkg/kf/sources/util.go
  pkg/kf/sources/util_test.go
  pkg/kf/sources/zz_generated.client.go
  pkg/kf/sources/zz_generated.clientoptions.go
Labels: cla: yes

#317 Quota space commands
  pkg/kf/commands/quotas/create.go
  pkg/kf/commands/quotas/create_test.go
  pkg/kf/commands/quotas/delete.go
  pkg/kf/commands/quotas/delete_test.go
  pkg/kf/commands/quotas/get.go
  pkg/kf/commands/quotas/get_test.go
  pkg/kf/commands/quotas/integration_test.go
  pkg/kf/commands/quotas/list.go
  pkg/kf/commands/quotas/list_test.go
  pkg/kf/commands/quotas/update.go
  pkg/kf/commands/quotas/update_test.go
  pkg/kf/commands/quotas/utils.go
  pkg/kf/commands/root.go
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/quotas/client.go
  pkg/kf/quotas/client.yml
  pkg/kf/quotas/doc.go
  pkg/kf/quotas/fake/fake_client.go
  pkg/kf/quotas/fake/interfaces.go
  pkg/kf/quotas/kfquota.go
  pkg/kf/quotas/zz_generated.client.go
  pkg/kf/quotas/zz_generated.clientoptions.go
  pkg/kf/spaces/kfspace.go
  pkg/kf/testutil/assertions.go
  pkg/kf/testutil/integration.go
Labels: cla: yes

#314 Vendor dependencies when running code generators.
  .gitignore
  ci/concourse/pipelines/pr-pipeline.yml
  go.mod
  go.sum
  hack/build.sh
  hack/check-code-generator.sh
  hack/codegen-packages.txt
  hack/setup-codegen.sh
  hack/update-codegen.sh
  pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
  pkg/client/build/clientset/versioned/clientset.go
  pkg/client/build/clientset/versioned/fake/clientset_generated.go
  pkg/client/build/clientset/versioned/typed/build/v1alpha1/build.go
  pkg/client/build/clientset/versioned/typed/build/v1alpha1/build_client.go
  pkg/client/build/clientset/versioned/typed/build/v1alpha1/buildtemplate.go
  pkg/client/build/clientset/versioned/typed/build/v1alpha1/clusterbuildtemplate.go
  pkg/client/build/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/kf/v1alpha1/app.go
  pkg/client/clientset/versioned/typed/kf/v1alpha1/kf_client.go
  pkg/client/clientset/versioned/typed/kf/v1alpha1/route.go
  pkg/client/clientset/versioned/typed/kf/v1alpha1/source.go
  pkg/client/clientset/versioned/typed/kf/v1alpha1/space.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  tools.go
Labels: cla: yes

#315 docs: Improve GKE instructions
  README.md
  docs/install.md
  docs/install/Kf-with-CloudRun-on-GKE.md
  docs/install/existing-cluster.md
  docs/install/gke.md
Labels: cla: yes

#323 added examples to proxy
  pkg/kf/commands/apps/proxy.go
  pkg/kf/commands/apps/proxy_test.go
Labels: cla: yes, docs

#326 moved buildpacks and stacks to use the buildpack on a space
  pkg/kf/buildpacks/client.go
  pkg/kf/buildpacks/client_test.go
  pkg/kf/buildpacks/fake/fake_client.go
  pkg/kf/commands/buildpacks/buildpacks.go
  pkg/kf/commands/buildpacks/buildpacks_test.go
  pkg/kf/commands/buildpacks/stacks.go
  pkg/kf/commands/buildpacks/stacks_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
Labels: bug, cla: yes

#325 pkg/kf/commands/app: adds restart command
  pkg/kf/apps/client.go
  pkg/kf/commands/apps/proxy.go
  pkg/kf/commands/apps/restart.go
  pkg/kf/commands/apps/restart_test.go
  pkg/kf/commands/apps/scale.go
  pkg/kf/commands/buildpacks/buildpacks.go
  pkg/kf/commands/buildpacks/stacks.go
  pkg/kf/commands/root.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/kfapps/client.go
  pkg/kf/kfapps/fake/fake_client.go
  pkg/reconciler/app/resources/knativeservice.go
Labels: cla: yes

#328 added service account to source
  pkg/apis/kf/v1alpha1/source_types.go
  pkg/reconciler/source/resources/build.go
  pkg/reconciler/source/resources/build_test.go
Labels: bug, cla: yes

#324 docs/apps: UAA deploy instructions
  docs/apps/README.md
  docs/apps/uaa/README.md
Labels: cla: yes

#331 Using anonymous auth for fetching images
  pkg/kf/buildpacks/client.go
Labels: cla: yes

#329 pkg/kf/commands/app: adds restage command
  pkg/kf/apps/client.go
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/commands/apps/restage.go
  pkg/kf/commands/apps/restage_test.go
  pkg/kf/commands/root.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
Labels: cla: yes

#334 pkg/kf/commands/apps: scale command without flags is a get
  pkg/kf/commands/apps/scale.go
  pkg/kf/commands/apps/scale_test.go
Labels: cla: yes

#341 Fix panic in proxy if app does not have route
  pkg/kf/commands/apps/proxy.go
  pkg/kf/commands/apps/proxy_test.go
Labels: cla: yes

#340 docs/apps: Spring Music deploy instructions
  docs/apps/README.md
  docs/apps/spring-music/README.md
  docs/apps/spring-music/sm1.png
  docs/apps/spring-music/sm2.png
  docs/install.md
Labels: cla: yes, docs

#343 pkg/kf/commands: adds version command
  hack/upload-release.sh
  pkg/kf/commands/root.go
  pkg/kf/commands/version.go
Labels: cla: yes

#346 pkg/kf/commands/apps: apps command uses SilenceUsage
  pkg/kf/commands/apps/apps.go
  pkg/kf/commands/apps/apps_test.go
Labels: cla: yes

#348 hacks: fix upload-release.sh script
  hack/upload-release.sh
Labels: cla: yes

#347 pkg/kf/testutil: use DOCKER_REGISTRY for integration tests
  hack/test.sh
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/testutil/integration.go
Labels: cla: yes

#349 fix target instructions
  docs/install/gke.md
Labels: cla: yes

#358 exted rather than replace env
  pkg/apis/kf/v1alpha1/source_defaults.go
Labels: cla: yes

#359 Fix problem in install.md
  docs/install.md
Labels: cla: yes

#342 pkg/reconciler/app: garbage collect revisions
  pkg/reconciler/app/controller.go
  pkg/reconciler/app/reconciler.go
Labels: cla: yes

#352 Add the --docker-image flag
  pkg/kf/apps/fake/fake_pusher.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
Labels: cla: yes

#350 started developer guide
  docs/developer-guide/README.md
  docs/developer-guide/configuring-routes.md
Labels: cla: yes, docs

#357 docs/uaa: local war build not required
  docs/apps/uaa/README.md
Labels: cla: yes

#364 docs: adds helloworld sample and references it
  docs/install.md
  samples/apps/echo/go.mod
  samples/apps/helloworld/go.mod
  samples/apps/helloworld/go.sum
  samples/apps/helloworld/main.go
Labels: cla: yes

#368 pkg/kf/commands/apps: adds start and stop commands
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/apps/start.go
  pkg/kf/commands/apps/start_test.go
  pkg/kf/commands/apps/stop.go
  pkg/kf/commands/apps/stop_test.go
  pkg/kf/commands/root.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/testutil/integration.go
  pkg/reconciler/app/reconciler.go
Labels: cla: yes

#369 pkg/kf/apps: adds --no-start flag to push
  pkg/kf/apps/client.go
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/apps/log_tailer.go
  pkg/kf/apps/log_tailer_test.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
Labels: cla: yes

#379 Remove duplicate error message
  cmd/kf/main.go
Labels: cla: yes

#380 Continue to watch on push to avoid push timeout
  pkg/kf/apps/log_tailer.go
  pkg/kf/apps/log_tailer_test.go
Labels: cla: yes

#385 Update README.md with correct link
  docs/developer-guide/README.md
Labels: cla: yes

#383 docs/uaa: Improve keys and certificates
  docs/apps/uaa/README.md
Labels: cla: yes, docs

#367 pkg/kf/commands/apps: use unique space for each integration test
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/testutil/integration.go
Labels: cla: yes

#370 pkg/kg/commands/app: adds integration test for --docker-file
  pkg/kf/commands/apps/integration_test.go
Labels: cla: yes

#386 Feature/manifest cleanup
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/apps/testdata/manifest.yml
  pkg/kf/manifest/manifest.go
  pkg/kf/manifest/manifest_test.go
Labels: cla: yes

#390 samples/apps: sample app manifest that deploys two apps
  samples/apps/multiple-apps/README.md
  samples/apps/multiple-apps/manifest.yml
Labels: cla: yes

#394 normalized diff for all clients
  pkg/kf/apps/zz_generated.client.go
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/internal/tools/clientgen/gentest/client_test.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/tmplfunctional.go
  pkg/kf/internal/tools/clientgen/tmplheader.go
  pkg/kf/routes/zz_generated.client.go
  pkg/kf/sources/zz_generated.client.go
  pkg/kf/spaces/zz_generated.client.go
Labels: cla: yes, enhancement

#392 adds domains field to spaces
  pkg/apis/kf/v1alpha1/alg_types.go
  pkg/apis/kf/v1alpha1/route_defaults.go
  pkg/apis/kf/v1alpha1/space_defaults.go
  pkg/apis/kf/v1alpha1/space_defaults_test.go
  pkg/apis/kf/v1alpha1/space_types.go
  pkg/apis/kf/v1alpha1/space_validation.go
  pkg/apis/kf/v1alpha1/space_validation_test.go
  pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/config_space_test.go
  pkg/kf/commands/spaces/create.go
  pkg/kf/commands/spaces/create_test.go
  pkg/kf/commands/spaces/get.go
  pkg/kf/commands/spaces/get_test.go
  pkg/kf/spaces/kfspace.go
  pkg/kf/spaces/kfspace_test.go
  pkg/reconciler/route/reconciler.go
  pkg/reconciler/route/resources/virtual_service_test.go
Labels: cla: yes

#402 Feature/describe output
  pkg/apis/kf/v1alpha1/app_validation.go
  pkg/kf/commands/apps/app.go
  pkg/kf/commands/apps/env.go
  pkg/kf/commands/apps/scale.go
  pkg/kf/commands/apps/scale_test.go
  pkg/kf/commands/root.go
  pkg/kf/commands/spaces/get.go
  pkg/kf/commands/spaces/get_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/describe/describe.go
  pkg/kf/describe/describe_test.go
  pkg/kf/describe/doc.go
  pkg/kf/describe/util.go
  pkg/kf/describe/util_test.go
Labels: cla: yes, cleanup, core commands

#406 add missing deepcopys
  pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
Labels: cla: yes

#404 Support `route` field in manifest
  pkg/apis/kf/v1alpha1/route_validation.go
  pkg/apis/kf/v1alpha1/route_validation_test.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/apps/testdata/manifest.yml
  pkg/kf/commands/routes/create_route.go
  pkg/kf/commands/routes/create_route_test.go
  pkg/kf/commands/routes/map_route.go
  pkg/kf/commands/routes/map_route_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/manifest/manifest.go
Labels: cla: yes

#407 Add explicit project ID to commands
  docs/install/gke.md
Labels: cla: yes

#338 Support auto-binding services specified in app manifest
  pkg/internal/envutil/envutil.go
  pkg/internal/envutil/envutil_test.go
  pkg/kf/apps/client.go
  pkg/kf/apps/kfapp.go
  pkg/kf/apps/push.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/env_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/apps/set_env_test.go
  pkg/kf/commands/apps/testdata/manifest-services.yaml
  pkg/kf/commands/apps/unset_env_test.go
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/config_space_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/internal/cfutil/vcapapp.go
  pkg/kf/manifest/manifest.go
  pkg/kf/service-bindings/client.go
  pkg/kf/service-bindings/client_test.go
  pkg/kf/service-bindings/fake/fake_client_interface.go
  pkg/kf/systemenvinjector/fake/fake_systemenvinjector.go
  pkg/kf/systemenvinjector/systemenvinjector.go
  pkg/kf/systemenvinjector/systemenvinjector_test.go
  pkg/reconciler/app/controller.go
  pkg/reconciler/app/reconciler.go
  pkg/reconciler/app/resources/knativeservice.go
Labels: cla: yes

#413 Set app default resource limits for memory, disk storage, and CPU
  pkg/apis/kf/v1alpha1/app_defaults.go
  pkg/apis/kf/v1alpha1/app_defaults_test.go
  pkg/kf/commands/apps/push_test.go
Labels: cla: yes

#414 Support health checks
  pkg/apis/kf/v1alpha1/app_defaults.go
  pkg/apis/kf/v1alpha1/app_defaults_test.go
  pkg/kf/apps/health_check.go
  pkg/kf/apps/health_check_test.go
  pkg/kf/apps/kfapp.go
  pkg/kf/apps/kfapp_test.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/commands/apps/app.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/apps/testdata/manifest.yml
  pkg/kf/describe/describe.go
  pkg/kf/describe/describe_test.go
  pkg/kf/manifest/manifest.go
Labels: cla: yes, enhancement

#428 adds helloworld gif to README.md
  README.md
  docs/images/helloworld.gif
Labels: cla: yes

#426 pkg/kf/commands/apps: push will create default route
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/apps/testdata/manifest.yml
  pkg/kf/manifest/manifest.go
  pkg/kf/testutil/assertions.go
Labels: cla: yes

#439 pkg/kf/commands/apps: ensure push can scale apps
  pkg/apis/kf/v1alpha1/route_types.go
  pkg/apis/kf/v1alpha1/route_types_test.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/apps.go
  pkg/kf/commands/apps/apps_test.go
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/apps/testdata/manifest.yml
  pkg/kf/manifest/manifest.go
  pkg/kf/testutil/integration.go
Labels: cla: yes
