Repository google/kf, pull requests merged in 2019-09, with the labels that each got.

#646 added service tags
  pkg/kf/cfutil/fake/fake_systemenvinjector.go
  pkg/kf/cfutil/systemenvinjector.go
  pkg/kf/cfutil/systemenvinjector_test.go
  pkg/kf/cfutil/vcap.go
  pkg/kf/cfutil/vcap_test.go
  pkg/kf/commands/service-bindings/integration_test.go
  samples/apps/service-broker/go.mod
  samples/apps/service-broker/go.sum
  samples/apps/service-broker/main.go
Labels: bug, cf compatibility, cla: yes

#647 fixed #607
  pkg/apis/kf/v1alpha1/app_lifecycle.go
  pkg/apis/kf/v1alpha1/app_lifecycle_test.go
  pkg/kf/apps/log_tailer.go
  pkg/reconciler/app/reconciler.go
Labels: cla: yes

#651 reduce default CPU
  pkg/apis/kf/v1alpha1/app_defaults.go
Labels: bug, cla: yes

#633 support namespaced brokers
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-service-broker.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-service.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-service-broker.md
  pkg/kf/commands/service-bindings/integration_test.go
  pkg/kf/commands/service-brokers/create-service-broker.go
  pkg/kf/commands/service-brokers/delete-service-broker.go
  pkg/kf/commands/services/create-service.go
  pkg/kf/commands/services/create-service_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/describe/describe.go
  pkg/kf/describe/describe_test.go
  pkg/kf/services/fake/fake_client_interface.go
  pkg/kf/services/services.go
  pkg/kf/services/services_test.go
Labels: cla: yes

#659 remove unused error
  pkg/kf/apps/push.go
Labels: cla: yes

#661 added docs for buildpacks
  docs/kf.dev/content/en/docs/developers/buildpacks/_index.md
  docs/kf.dev/content/en/docs/developers/buildpacks/go.md
  docs/kf.dev/content/en/docs/developers/buildpacks/java.md
  docs/kf.dev/content/en/docs/developers/buildpacks/node.md
Labels: cla: yes

#657 added app manifest docs
  docs/kf.dev/content/en/docs/developers/develop-and-manage-apps/kf-push/app-manifests/_index.md
Labels: cla: yes, docs

#662 Feature/refactor dsb
  pkg/kf/commands/service-brokers/delete-service-broker.go
Labels: cla: yes, cleanup

#658 added docs for domains
  docs/kf.dev/content/en/docs/operators/administering-kf/setting-up-a-custom-domain.md
Labels: cla: yes, docs

#666 Add message in asynchronous commands
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/_index.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-service-broker.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-service-broker.md
  pkg/kf/commands/apps/delete.go
  pkg/kf/commands/apps/restart.go
  pkg/kf/commands/apps/scale.go
  pkg/kf/commands/apps/set_env.go
  pkg/kf/commands/apps/set_env_test.go
  pkg/kf/commands/apps/start.go
  pkg/kf/commands/apps/stop.go
  pkg/kf/commands/apps/unset_env.go
  pkg/kf/commands/apps/unset_env_test.go
  pkg/kf/commands/routes/create_route.go
  pkg/kf/commands/routes/delete_route.go
  pkg/kf/commands/routes/map_route.go
  pkg/kf/commands/routes/unmap_route.go
  pkg/kf/commands/service-bindings/unbind-service.go
  pkg/kf/commands/service-brokers/create-service-broker.go
  pkg/kf/commands/service-brokers/delete-service-broker.go
  pkg/kf/commands/services/create-service.go
  pkg/kf/commands/services/delete-service.go
  pkg/kf/commands/spaces/delete.go
  pkg/kf/commands/utils/utils.go
Labels: cla: yes

#669 Merge Master
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/_index.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-service-broker.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-service-broker.md
  docs/kf.dev/content/en/docs/operators/administering-kf/setting-up-a-custom-domain.md
  pkg/kf/commands/apps/delete.go
  pkg/kf/commands/apps/restart.go
  pkg/kf/commands/apps/scale.go
  pkg/kf/commands/apps/set_env.go
  pkg/kf/commands/apps/set_env_test.go
  pkg/kf/commands/apps/start.go
  pkg/kf/commands/apps/stop.go
  pkg/kf/commands/apps/unset_env.go
  pkg/kf/commands/apps/unset_env_test.go
  pkg/kf/commands/routes/create_route.go
  pkg/kf/commands/routes/delete_route.go
  pkg/kf/commands/routes/map_route.go
  pkg/kf/commands/routes/unmap_route.go
  pkg/kf/commands/service-bindings/unbind-service.go
  pkg/kf/commands/service-brokers/create-service-broker.go
  pkg/kf/commands/service-brokers/delete-service-broker.go
  pkg/kf/commands/services/create-service.go
  pkg/kf/commands/services/delete-service.go
  pkg/kf/commands/spaces/delete.go
  pkg/kf/commands/utils/utils.go
Labels: cla: yes

#670 Fix services cmd and add issue numbers to skipped int tests
  pkg/kf/commands/service-bindings/integration_test.go
  pkg/kf/commands/services/services.go
  pkg/kf/services/services.go
Labels: cla: yes

#672 Release/0.1.0
  CHANGELOG.md
  pkg/kf/commands/service-bindings/integration_test.go
  pkg/kf/commands/services/services.go
  pkg/kf/services/services.go
Labels: cla: yes

#667 docs: Add dependencies/architecture doc
  docs/kf.dev/content/en/docs/general-info/kf-dependencies/_index.md
  docs/kf.dev/content/en/docs/general-info/kf-dependencies/diagram.svg
Labels: cla: yes

#682 hack: ensure GOPATH and auth when releasing
  hack/build-release.sh
  hack/upload-release.sh
Labels: cla: yes

#681 pkg/kf/commands/install/kf: pick kf release
  go.mod
  go.sum
  pkg/kf/commands/install/kf/kf.go
Labels: cla: yes

#679 moved to using k8s yaml parser everywhere
  go.mod
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/config/config.go
  pkg/kf/describe/describe.go
  pkg/kf/internal/tools/clientgen/client.go
  pkg/kf/internal/tools/clientgen/genclient.go
  pkg/kf/internal/tools/option-builder/option-builder.go
  pkg/kf/manifest/manifest.go
Labels: cla: yes

#691 added the ability to select a stack
  docs/kf.dev/content/en/docs/developers/develop-and-manage-apps/kf-push/app-manifests/_index.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_push.md
  pkg/apis/kf/v1alpha1/source_lifecycle.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/manifest/manifest.go
  pkg/kf/manifest/manifest_test.go
  pkg/kf/sources/kfsource.go
  pkg/kf/sources/kfsource_test.go
  pkg/reconciler/source/resources/build.go
  pkg/reconciler/source/resources/build_test.go
  third_party/VENDOR-LICENSE
Labels: cf compatibility, cla: yes, enhancement

#693 Allow printing with k8s printers
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_app.md
  go.mod
  go.sum
  pkg/kf/commands/apps/app.go
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/testutil/integration.go
  third_party/VENDOR-LICENSE
Labels: cla: yes

#668 updated generators
  pkg/kf/apps/client.go
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/apps/zz_generated.client.go
  pkg/kf/commands/apps/scale.go
  pkg/kf/commands/apps/scale_test.go
  pkg/kf/commands/apps/set_env.go
  pkg/kf/commands/apps/set_env_test.go
  pkg/kf/commands/apps/start.go
  pkg/kf/commands/apps/start_test.go
  pkg/kf/commands/apps/stop.go
  pkg/kf/commands/apps/stop_test.go
  pkg/kf/commands/apps/unset_env.go
  pkg/kf/commands/apps/unset_env_test.go
  pkg/kf/commands/quotas/delete.go
  pkg/kf/commands/quotas/delete_test.go
  pkg/kf/commands/quotas/update.go
  pkg/kf/commands/quotas/update_test.go
  pkg/kf/commands/routes/delete_route_test.go
  pkg/kf/commands/routes/map_route.go
  pkg/kf/commands/routes/map_route_test.go
  pkg/kf/commands/routes/unmap_route.go
  pkg/kf/commands/routes/unmap_route_test.go
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/config_space_test.go
  pkg/kf/internal/tools/clientgen/gentest/client.go
  pkg/kf/internal/tools/clientgen/gentest/client_test.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/tmplclient.go
  pkg/kf/routeclaims/client.go
  pkg/kf/routeclaims/fake/fake_client.go
  pkg/kf/routeclaims/zz_generated.client.go
  pkg/kf/routes/client.go
  pkg/kf/routes/fake/fake_client.go
  pkg/kf/routes/zz_generated.client.go
  pkg/kf/service-bindings/client.go
  pkg/kf/service-bindings/client_test.go
  pkg/kf/sources/client.go
  pkg/kf/sources/fake/fake_client.go
  pkg/kf/sources/zz_generated.client.go
  pkg/kf/spaces/client.go
  pkg/kf/spaces/fake/fake_client.go
  pkg/kf/spaces/zz_generated.client.go
Labels: cla: yes

#694 added support for the legacy buildpack field
  pkg/kf/manifest/manifest.go
  pkg/kf/manifest/manifest_test.go
Labels: cf compatibility, cla: yes

#701 removed unused generator options
  pkg/kf/apps/client.go
  pkg/kf/apps/zz_generated.client.go
  pkg/kf/apps/zz_generated.clientoptions.go
  pkg/kf/commands/routes/delete_route.go
  pkg/kf/internal/tools/clientgen/common-options.yml
  pkg/kf/internal/tools/clientgen/gentest/client.go
  pkg/kf/internal/tools/clientgen/gentest/client_test.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.clientoptions.go
  pkg/kf/internal/tools/clientgen/tmplclient.go
  pkg/kf/internal/tools/clientgen/tmplfunctional.go
  pkg/kf/routeclaims/client.go
  pkg/kf/routeclaims/zz_generated.client.go
  pkg/kf/routeclaims/zz_generated.clientoptions.go
  pkg/kf/routes/client.go
  pkg/kf/routes/zz_generated.client.go
  pkg/kf/routes/zz_generated.clientoptions.go
  pkg/kf/sources/client.go
  pkg/kf/sources/zz_generated.client.go
  pkg/kf/sources/zz_generated.clientoptions.go
  pkg/kf/spaces/client.go
  pkg/kf/spaces/zz_generated.client.go
  pkg/kf/spaces/zz_generated.clientoptions.go
Labels: cla: yes, cleanup

#695 Feature/manifest commands
  docs/kf.dev/content/en/docs/developers/develop-and-manage-apps/kf-push/app-manifests/_index.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_push.md
  pkg/kf/apps/kfapp.go
  pkg/kf/apps/kfapp_test.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/manifest/manifest.go
  pkg/kf/manifest/manifest_test.go
  pkg/kf/manifest/manifest_validation.go
  pkg/kf/manifest/manifest_validation_test.go
Labels: cf compatibility, cla: yes, enhancement

#700 added forwarding headers
  pkg/reconciler/route/resources/virtual_service.go
  pkg/reconciler/route/resources/virtual_service_test.go
Labels: cla: yes

#704 Feature/watcher closures
  pkg/kf/apps/client.go
  pkg/kf/apps/client.yml
  pkg/kf/apps/client_test.go
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/apps/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/client.go
  pkg/kf/internal/tools/clientgen/gentest/client.go
  pkg/kf/internal/tools/clientgen/gentest/client.yml
  pkg/kf/internal/tools/clientgen/gentest/client_test.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/tmplclient.go
  pkg/kf/internal/tools/clientgen/tmplfunctional.go
  pkg/kf/internal/tools/clientgen/tmplheader.go
  pkg/kf/routeclaims/fake/fake_client.go
  pkg/kf/routeclaims/zz_generated.client.go
  pkg/kf/routes/fake/fake_client.go
  pkg/kf/routes/zz_generated.client.go
  pkg/kf/service-bindings/client.go
  pkg/kf/sources/fake/fake_client.go
  pkg/kf/sources/zz_generated.client.go
  pkg/kf/spaces/fake/fake_client.go
  pkg/kf/spaces/zz_generated.client.go
Labels: cla: yes, enhancement

#707 Move Bindings to App
  pkg/kf/apps/client.go
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/apps/util.go
  pkg/kf/apps/util_test.go
  pkg/kf/builds/builtins.go
  pkg/kf/builds/client.go
  pkg/kf/builds/client_test.go
  pkg/kf/builds/doc.go
  pkg/kf/builds/fake/fake_client.go
  pkg/kf/builds/fake/interfaces.go
  pkg/kf/builds/options.go
  pkg/kf/builds/options.yml
  pkg/kf/builds/util.go
  pkg/kf/builds/util_test.go
  pkg/kf/commands/config/config.go
  pkg/kf/commands/service-bindings/bind-service.go
  pkg/kf/commands/service-bindings/bind-service_test.go
  pkg/kf/commands/service-bindings/unbind-service.go
  pkg/kf/commands/service-bindings/unbind-service_test.go
  pkg/kf/commands/services/create-service.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/secrets/fake/fake_client_interface.go
  pkg/kf/secrets/fake/interfaces.go
  pkg/kf/secrets/options.go
  pkg/kf/secrets/options.yml
  pkg/kf/secrets/secrets.go
  pkg/kf/secrets/secrets_test.go
  pkg/kf/secrets/utils.go
  pkg/kf/secrets/utils_test.go
  pkg/kf/service-bindings/client.go
  pkg/kf/service-bindings/client_test.go
  pkg/kf/service-bindings/fake/fake_client_interface.go
  pkg/kf/service-bindings/options.go
  pkg/kf/service-bindings/options.yml
  pkg/kf/services/fake/fake_client.go
  pkg/kf/services/utils.go
  pkg/kf/services/utils_test.go
  pkg/kf/services/zz_generated.client.go
Labels: cla: yes

#710 ci: Improve code generation script
  ci/concourse/pipelines/pr-pipeline.yml
  hack/check-code-generator.sh
Labels: cla: yes, cleanup

#702 third_party: k8s.io/kubernetes/pkg/kubectl/util/templates
  go.mod
  go.sum
  pkg/kf/commands/root.go
  third_party/kubectl-templates/README.md
  third_party/kubectl-templates/markdown.go
  third_party/kubectl-templates/normalizers.go
Labels: cla: yes

#711 Added standard async flag
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_bind-service.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_restage.md
  pkg/kf/commands/apps/delete.go
  pkg/kf/commands/apps/delete_test.go
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/apps/restage.go
  pkg/kf/commands/apps/restage_test.go
  pkg/kf/commands/service-bindings/bind-service.go
  pkg/kf/internal/utils/cli/async_flags.go
  pkg/kf/internal/utils/cli/async_flags_test.go
  pkg/kf/testutil/integration.go
Labels: cf compatibility, cla: yes

#713 fix bash vs sh failure
  hack/check-code-generator.sh
Labels: bug, cla: yes
