Repository google/kf, pull requests merged in 2019-06, with the labels that each got.

#121 Fix manifest integration test
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/testutil/integration.go
Labels: cla: yes

#119 pkg/kf/commands/apps: fix manifest integration test
  pkg/kf/commands/apps/integration_test.go
Labels: cla: yes

#122 pkg/kf/commands: removes KfParams.Output
  pkg/kf/commands/apps/apps.go
  pkg/kf/commands/apps/apps_test.go
  pkg/kf/commands/apps/delete_test.go
  pkg/kf/commands/apps/env.go
  pkg/kf/commands/apps/env_test.go
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/apps/proxy.go
  pkg/kf/commands/apps/proxy_test.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/apps/set_env_test.go
  pkg/kf/commands/apps/unset_env_test.go
  pkg/kf/commands/buildpacks/buildpacks.go
  pkg/kf/commands/buildpacks/buildpacks_test.go
  pkg/kf/commands/buildpacks/upload_buildpacks_test.go
  pkg/kf/commands/config/config.go
  pkg/kf/commands/doctor/doctor.go
  pkg/kf/commands/doctor/doctor_test.go
  pkg/kf/commands/root.go
  pkg/kf/commands/service-bindings/bind-service.go
  pkg/kf/commands/service-bindings/bindings.go
  pkg/kf/commands/service-bindings/cli_test.go
  pkg/kf/commands/service-bindings/vcap_services.go
  pkg/kf/commands/services/create-service.go
  pkg/kf/commands/services/helpers_test.go
  pkg/kf/commands/services/marketplace.go
  pkg/kf/commands/services/service.go
  pkg/kf/commands/services/services.go
  pkg/kf/commands/spaces/create_test.go
  pkg/kf/commands/spaces/delete_test.go
  pkg/kf/commands/spaces/list.go
  pkg/kf/commands/spaces/list_test.go
Labels: cla: yes, cleanup

#124 Feature/deploy to apps client
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/deploy.go
  pkg/kf/deploy_test.go
  pkg/kf/fake/fake_deployer.go
  pkg/kf/fake/fake_lister.go
  pkg/kf/fake/interfaces.go
  pkg/kf/list.go
  pkg/kf/list_test.go
  pkg/kf/options.go
  pkg/kf/options.yml
  pkg/kf/push_test.go
Labels: cla: yes, cleanup

#127 pkg/kf/logs: adds logs functionality
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/apps/logs.go
  pkg/kf/commands/apps/logs_test.go
  pkg/kf/commands/root.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/logs/doc.go
  pkg/kf/logs/fake/fake_logs.go
  pkg/kf/logs/fake/interface.go
  pkg/kf/logs/options.go
  pkg/kf/logs/options.yml
  pkg/kf/logs/tailer.go
  pkg/kf/logs/tailer_test.go
  pkg/kf/testutil/integration.go
  samples/apps/echo/README.md
  samples/apps/echo/main.go
Labels: cla: yes

#130 pkg/kf/commands: group command names
  go.mod
  go.sum
  pkg/kf/commands/root.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/logs/tailer.go
Labels: cla: yes, docs, enhancement

#131 pkg/kf/logs: time out for app without a container
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/logs/tailer.go
Labels: cla: yes

#136 updated readme and install instructions
  README.md
  docs/install.md
Labels: cla: yes, docs

#138 added controller docs
  docs/development/README.md
  docs/development/crd-controllers.md
Labels: cla: yes, docs

#146 docs: prefers docs directory for install docs
  install.md
Labels: cla: yes

#145 Push now builds before creating a Knative service.
  docs/differences.md
  pkg/kf/builds/client.go
  pkg/kf/builds/client_test.go
  pkg/kf/builds/fake/fake_client.go
  pkg/kf/builds/options.go
  pkg/kf/builds/options.yml
  pkg/kf/builds/util.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/utils/command_override_fetcher.go
  pkg/kf/commands/utils/command_override_fetcher_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/log_tailer.go
  pkg/kf/log_tailer_test.go
  pkg/kf/push.go
  pkg/kf/push_test.go
Labels: cla: yes

#155 pkg/kf/commands/buildpacks: list correctly
  go.mod
  pkg/kf/buildpacks/client.go
  pkg/kf/buildpacks/client_test.go
  pkg/kf/buildpacks/fake/fake_client.go
  pkg/kf/buildpacks/fake_image_test.go
  pkg/kf/commands/buildpacks/buildpacks.go
  pkg/kf/commands/buildpacks/buildpacks_test.go
Labels: cla: yes

#160 pkg/kf/commands: removes remote plugins
  pkg/kf/commands/root.go
  pkg/kf/commands/utils/command_override_fetcher.go
  pkg/kf/commands/utils/command_override_fetcher_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  samples/plugins/gke/README.md
  samples/plugins/gke/cmd/generator/main.go
  samples/plugins/gke/cmd/prefix-output/go.mod
  samples/plugins/gke/cmd/prefix-output/go.sum
  samples/plugins/gke/cmd/prefix-output/main.go
  samples/plugins/gke/cmd/push/go.mod
  samples/plugins/gke/cmd/push/go.sum
  samples/plugins/gke/cmd/push/integration_test.go
  samples/plugins/gke/cmd/push/main.go
  samples/plugins/gke/pkg/commands/push.go
  samples/plugins/gke/push-images.sh
  samples/plugins/gke/tests.sh
Labels: cla: yes

#163 pkg/kf/commands/apps: fix flaky/broken integration tests
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/testutil/integration.go
Labels: cla: yes

#164 moved push to use getters/setters on kfapp
  pkg/kf/apps/kfapp.go
  pkg/kf/apps/kfapp_test.go
  pkg/kf/deploy_test.go
  pkg/kf/push.go
Labels: cla: yes, cleanup

#165 pkg/kf/testutil: fix bug in RetryOnPanic
  pkg/kf/testutil/integration.go
Labels: cla: yes

#173 fixed #170
  pkg/kf/commands/apps/apps.go
  pkg/kf/commands/apps/apps_test.go
Labels: cla: yes, cleanup

#167 hack: ensure failure message is displayed
  hack/test.sh
Labels: cla: yes

#200 pkg/kf/commands/apps: skips env overwrite test
  pkg/kf/commands/apps/integration_test.go
Labels: cla: yes

#171 upgraded to knative serving 0.6
  docs/install.md
  go.mod
  go.sum
  pkg/kf/apps/kfapp.go
  pkg/kf/commands/apps/apps.go
  pkg/kf/commands/apps/apps_test.go
  pkg/kf/commands/apps/proxy.go
  pkg/kf/internal/envutil/envutil.go
  pkg/kf/log_tailer_test.go
  pkg/kf/push_test.go
  pkg/kf/systemenvinjector/systemenvinjector_test.go
Labels: cla: yes, cleanup

#189 docs/install: adds docs for GKE+CR
  docs/install/Kf-with-CloudRun-on-GKE.md
Labels: cla: yes

#142 added space lifecycle
  pkg/apis/kf/v1alpha1/space_lifecycle.go
  pkg/apis/kf/v1alpha1/space_lifecycle_test.go
Labels: cla: yes, enhancement

#162 add kf space quota commands and tests
  go.mod
  go.sum
  pkg/kf/commands/quotas/create.go
  pkg/kf/commands/quotas/create_test.go
  pkg/kf/commands/quotas/delete.go
  pkg/kf/commands/quotas/delete_test.go
  pkg/kf/commands/quotas/get.go
  pkg/kf/commands/quotas/get_test.go
  pkg/kf/commands/quotas/list.go
  pkg/kf/commands/quotas/list_test.go
  pkg/kf/commands/quotas/update.go
  pkg/kf/commands/quotas/update_test.go
  pkg/kf/commands/quotas/utils.go
  pkg/kf/commands/root.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/quotas/client.go
  pkg/kf/quotas/client.yml
  pkg/kf/quotas/doc.go
  pkg/kf/quotas/fake/fake_client.go
  pkg/kf/quotas/fake/interfaces.go
  pkg/kf/quotas/kfquota.go
  pkg/kf/quotas/zz_generated.client.go
  pkg/kf/quotas/zz_generated.clientoptions.go
  pkg/kf/testutil/assertions.go
Labels: cla: yes

#188 hack: publish the stack when uploading buildpacks
  hack/upload-buildpacks-stack.sh
  hack/upload-buildpacks.sh
Labels: cla: yes

#205 Fix create quota command
  pkg/kf/commands/quotas/create.go
Labels: cla: yes

#217 remove spammy github comment
  ci/concourse/pipelines/kf-pipeline.yml
Labels: cla: yes

#220 pkg/kf/commands/routes: fix bug in deleting route
  pkg/kf/commands/routes/delete_route.go
  pkg/kf/commands/routes/delete_route_test.go
Labels: bug, cla: yes

#223 Add ko to the CI container image
  ci/concourse/image/Dockerfile
Labels: cla: yes

#222 Add ko apply step to concourse
  ci/concourse/pipelines/pr-pipeline.yml
  config/300-app.yaml
  config/300-source.yaml
  hack/setup-codegen.sh
  hack/update-codegen.sh
Labels: cla: yes

#224 moved spaces command to use kf.Space
  config/300-space.yaml
  pkg/kf/commands/spaces/create.go
  pkg/kf/commands/spaces/create_test.go
  pkg/kf/commands/spaces/list.go
  pkg/kf/commands/spaces/list_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/spaces/client.go
  pkg/kf/spaces/client.yml
  pkg/kf/spaces/fake/fake_client.go
  pkg/kf/spaces/kfspace.go
  pkg/kf/spaces/kfspace_test.go
  pkg/kf/spaces/zz_generated.client.go
Labels: cla: yes, enhancement

#228 Add concourse cleanup job
  ci/concourse/pipelines/kf-pipeline.yml
Labels: cla: yes

#230 added ability to load/save config and target spaces closes #26
  go.mod
  go.sum
  pkg/kf/commands/config/config.go
  pkg/kf/commands/config/config_test.go
  pkg/kf/commands/config/testdata/custom-config.yml
  pkg/kf/commands/config/testdata/empty-config.yml
  pkg/kf/commands/root.go
  pkg/kf/commands/target.go
Labels: cla: yes

#218 quota integration tests
  pkg/kf/commands/quotas/integration_test.go
  pkg/kf/doctor/cluster.go
  pkg/kf/testutil/integration.go
Labels: cla: yes

#232 Upgrade to Knative.dev/pkg
  cmd/controller/main.go
  go.mod
  go.sum
  hack/check-go-generate.sh
  hack/setup-codegen.sh
  hack/update-codegen.sh
  pkg/apis/kf/v1alpha1/app_types.go
  pkg/apis/kf/v1alpha1/space_lifecycle.go
  pkg/apis/kf/v1alpha1/space_lifecycle_test.go
  pkg/apis/kf/v1alpha1/space_types.go
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  pkg/client/injection/informers/kf/factory/fake/fake.go
  pkg/client/injection/informers/kf/factory/kffactory.go
  pkg/client/injection/informers/kf/v1alpha1/space/fake/fake.go
  pkg/client/injection/informers/kf/v1alpha1/space/space.go
  pkg/kf/commands/config/config.go
  pkg/kf/commands/routes/create_route.go
  pkg/kf/commands/routes/create_route_test.go
  pkg/kf/commands/routes/routes_test.go
  pkg/kf/commands/spaces/list_test.go
  pkg/kf/routes/client.go
  pkg/kf/routes/client.yml
  pkg/kf/routes/fake/fake_client.go
  pkg/kf/routes/zz_generated.client.go
  pkg/reconciler/base.go
  pkg/reconciler/space/controller.go
  pkg/reconciler/space/reconciler.go
  pkg/reconciler/space/resources/namespace.go
  pkg/reconciler/space/resources/role.go
Labels: cla: yes

#231 added docs for push
  docs/spec/README.md
  docs/spec/app_push.md
  docs/spec/images/push.mmd
  docs/spec/images/push.svg
Labels: cla: yes, docs

#233 Fix hack/upddate-codegen
  go.sum
  hack/setup-codegen.sh
  hack/update-codegen.sh
  pkg/apis/kf/v1alpha1/app_types.go
  pkg/client/injection/informers/kf/v1alpha1/app/app.go
  pkg/client/injection/informers/kf/v1alpha1/app/fake/fake.go
  pkg/client/injection/informers/kf/v1alpha1/source/fake/fake.go
  pkg/client/injection/informers/kf/v1alpha1/source/source.go
Labels: cla: yes

#236 go: use latest github.com/poy/kontext
  go.mod
  go.sum
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
Labels: cla: yes

#234 fix push being slow
  pkg/kf/log_tailer.go
  pkg/kf/log_tailer_test.go
  pkg/kf/push.go
Labels: bug, cla: yes

#235 Add hack/check-code-generator
  ci/concourse/pipelines/pr-pipeline.yml
  hack/check-code-generator.sh
Labels: cla: yes

#239 all: use fork of github.com/knative/pkg
  go.mod
  go.sum
Labels: cla: yes
