Repository google/kf, pull requests merged in 2019-08, with the labels that each got.

#452 Replaced wget command with curl in mac install instructions
  docs/install.md
Labels: cla: yes

#448 pkg/kf/commands/apps: allow for path to point to a file
  go.mod
  go.sum
  pkg/kf/commands/apps/push.go
Labels: cla: yes

#421 Support disk_quota, memory, and CPU in app manifest
  pkg/kf/apps/kfapp.go
  pkg/kf/apps/kfapp_test.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/app.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/apps/testdata/manifest.yml
  pkg/kf/describe/describe.go
  pkg/kf/describe/describe_test.go
  pkg/kf/manifest/manifest.go
Labels: cla: yes

#422 Adds ability to poll until a predicate is done
  pkg/apis/kf/v1alpha1/utils.go
  pkg/apis/kf/v1alpha1/utils_test.go
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/apps/zz_generated.client.go
  pkg/kf/commands/spaces/create.go
  pkg/kf/commands/spaces/create_test.go
  pkg/kf/internal/tools/clientgen/gentest/client_test.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/tmplclient.go
  pkg/kf/internal/tools/clientgen/tmplheader.go
  pkg/kf/routes/fake/fake_client.go
  pkg/kf/routes/zz_generated.client.go
  pkg/kf/sources/fake/fake_client.go
  pkg/kf/sources/zz_generated.client.go
  pkg/kf/spaces/client.go
  pkg/kf/spaces/fake/fake_client.go
  pkg/kf/spaces/zz_generated.client.go
Labels: cla: yes

#446 pkg/reconciler: AppStatus doesn't display stale Source
  pkg/apis/kf/v1alpha1/source_lifecycle.go
  pkg/apis/kf/v1alpha1/utils.go
  pkg/apis/kf/v1alpha1/utils_test.go
  pkg/kf/commands/apps/integration_test.go
  pkg/reconciler/source/reconciler.go
Labels: cla: yes

#453 add getters for space config
  go.mod
  pkg/apis/kf/v1alpha1/space_types.go
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/config_space_test.go
Labels: cla: yes, enhancement

#449 pkg/kf/commands/install: adds installer for GKE
  docs/install.md
  docs/install/gke.md
  go.mod
  go.sum
  pkg/kf/commands/install/gke/gke.go
  pkg/kf/commands/install/go.mod
  pkg/kf/commands/install/go.sum
  pkg/kf/commands/install/install.go
  pkg/kf/commands/install/kf/kf.go
  pkg/kf/commands/install/util/util.go
  pkg/kf/commands/root.go
Labels: cla: yes

#477 fix client-go pseudoversion
  go.mod
  go.sum
Labels: cla: yes

#468 started issue templates
  .github/ISSUE_TEMPLATE/ask-question.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull-request-template.md
  SECURITY.md
Labels: cla: yes, docs

#476 revert v0.7.0 knative build upgrade
  docs/install.md
  pkg/kf/commands/install/kf/kf.go
Labels: cla: yes

#478 revert GKE version for docs and installer
  docs/install/gke.md
  pkg/kf/commands/install/gke/gke.go
Labels: cla: yes

#480 fix grammar in manifest warning
  pkg/kf/manifest/manifest.go
Labels: cla: yes

#479 added debug command
  pkg/kf/commands/debug.go
  pkg/kf/commands/root.go
Labels: cla: yes

#481 added proposal template
  .github/ISSUE_TEMPLATE/proposal.md
Labels: cla: yes

#484 Install: register gcloud as a Docker credential
  docs/install/gke.md
Labels: cla: yes

#485 Samples vs current sample
  docs/install.md
Labels: cla: yes

#487 pkg/kf/commands/apps: fix StopStart integration tests
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/testutil/integration.go
Labels: cla: yes

#483 Move env injection into secret
  pkg/apis/kf/v1alpha1/app_lifecycle.go
  pkg/apis/kf/v1alpha1/utils.go
  pkg/reconciler/app/controller.go
  pkg/reconciler/app/reconciler.go
  pkg/reconciler/app/resources/knativeservice.go
  pkg/reconciler/app/resources/secret.go
  pkg/reconciler/app/resources/secret_test.go
Labels: cla: yes

#491 Do not require source to install service catalog
  docs/install.md
Labels: cla: yes

#488 docs: remove node artifacts
  docs/kf.dev/package-lock.json
  docs/kf.dev/package.json
Labels: cla: yes

#494 pkg/kf/commands/install: ensure knative build installs first
  pkg/kf/commands/install/kf/kf.go
Labels: cla: yes

#489 pkg/kf/commands/spaces: adds test for number of args
  pkg/kf/commands/spaces/config_space_test.go
Labels: cla: yes

#501 pkg/kf/testutil: prefix failure messages with test name
  pkg/kf/doctor/diagnostic.go
  pkg/kf/testutil/assertions.go
Labels: cla: yes

#507 hack: only run misspell on go files
  hack/check-linters.sh
Labels: cla: yes

#503 docs/ci: add CI to build and push static site
  docs/kf.dev/ci/concourse/README.md
  docs/kf.dev/ci/concourse/image/Dockerfile
  docs/kf.dev/ci/concourse/pipelines/website-pipeline.yml
Labels: cla: yes

#505 Docs: Add Install, Minibroker, and Spring Music to Getting Started
  docs/kf.dev/content/en/docs/getting-started/install/_index.md
  docs/kf.dev/content/en/docs/getting-started/minibroker/_index.md
  docs/kf.dev/content/en/docs/getting-started/spring-music/_index.md
  docs/kf.dev/content/en/docs/getting-started/spring-music/sm1.png
  docs/kf.dev/content/en/docs/getting-started/spring-music/sm2.png
Labels: cla: yes

#509 Single-character flag needs only single leading '-'
  pkg/kf/commands/apps/scale.go
Labels: cla: yes

#508 pkg/apis/kf/v1alpha1: default EnableDeveloperLogsAccess to true
  pkg/apis/kf/v1alpha1/space_defaults.go
  pkg/apis/kf/v1alpha1/space_defaults_test.go
Labels: cla: yes

#506 ci/concourse/pipeline: adds release job
  ci/concourse/pipelines/kf-pipeline.yml
  hack/README.md
  hack/build-release.sh
  hack/upload-release.sh
Labels: cla: yes

#513 pkg/kf/commands/config: lazily return kube config errors
  pkg/kf/commands/config/config.go
Labels: cla: yes

#512 Persist service catalog info
  docs/install.md
  third_party/service-catalog/manifests/catalog/templates/apiregistration.yaml
  third_party/service-catalog/manifests/catalog/templates/apiserver-deployment.yaml
  third_party/service-catalog/manifests/catalog/templates/etcd-pvc.yaml
  third_party/service-catalog/values/catalog.yml
Labels: cla: yes

#516 docs: Google service broker installation
  docs/kf.dev/content/en/docs/operators/service-brokers/_index.md
  docs/kf.dev/content/en/docs/operators/service-brokers/google-cloud/_index.md
  third_party/gcp-service-broker/.gitignore
  third_party/gcp-service-broker/.helmignore
  third_party/gcp-service-broker/README.md
  third_party/gcp-service-broker/cf-tutorial.md
  third_party/gcp-service-broker/charts/mysql-0.15.0.tgz
  third_party/gcp-service-broker/gcp-service-broker-5.0.0.tgz
  third_party/gcp-service-broker/templates/NOTES.txt
  third_party/gcp-service-broker/templates/_helpers.tpl
  third_party/gcp-service-broker/templates/clusterservicebroker.yaml
  third_party/gcp-service-broker/templates/deployment.yaml
  third_party/gcp-service-broker/templates/ingress.yaml
  third_party/gcp-service-broker/templates/secrets.yaml
  third_party/gcp-service-broker/templates/service.yaml
  third_party/gcp-service-broker/templates/tests/test-connection.yaml
Labels: cla: yes

#514 Add unit test cases for app lifecycle
  pkg/apis/kf/v1alpha1/app_lifecycle.go
  pkg/apis/kf/v1alpha1/app_lifecycle_test.go
Labels: cla: yes

#496 sources now run once
  hack/test.sh
  pkg/apis/kf/v1alpha1/app_defaults.go
  pkg/apis/kf/v1alpha1/app_defaults_test.go
  pkg/apis/kf/v1alpha1/app_masks.go
  pkg/apis/kf/v1alpha1/app_masks_test.go
  pkg/apis/kf/v1alpha1/app_validation.go
  pkg/apis/kf/v1alpha1/app_validation_test.go
  pkg/apis/kf/v1alpha1/source_defaults.go
  pkg/apis/kf/v1alpha1/source_types.go
  pkg/apis/kf/v1alpha1/source_types_test.go
  pkg/apis/kf/v1alpha1/source_validation.go
  pkg/apis/kf/v1alpha1/source_validation_test.go
  pkg/apis/kf/v1alpha1/space_types.go
  pkg/kf/apps/log_tailer.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/describe/describe.go
  pkg/kf/describe/describe_test.go
  pkg/kf/sources/kfsource.go
  pkg/kf/sources/kfsource_test.go
  pkg/kf/testutil/assertions.go
  pkg/kf/testutil/integration.go
  pkg/reconciler/app/reconciler.go
  pkg/reconciler/app/resources/source.go
  pkg/reconciler/app/resources/source_test.go
  pkg/reconciler/base.go
  pkg/reconciler/route/reconciler.go
  pkg/reconciler/source/reconciler.go
  pkg/reconciler/source/resources/build.go
  pkg/reconciler/source/resources/build_test.go
Labels: bug, cla: yes

#528 fix broken master
  pkg/apis/kf/v1alpha1/app_lifecycle_test.go
Labels: cla: yes

#523 Docs: Add Awwvision
  docs/kf.dev/content/en/docs/developers/reference-apps/awwvision/_index.md
Labels: cla: yes

#517 docs: Add Link Shortener reference app
  docs/kf.dev/content/en/docs/developers/reference-apps/_index.md
  docs/kf.dev/content/en/docs/developers/reference-apps/link-shortener/_index.md
  docs/kf.dev/content/en/docs/developers/reference-apps/link-shortener/external.png
  docs/kf.dev/content/en/docs/developers/reference-apps/link-shortener/landing.png
Labels: cla: yes

#526 docs: Add default env var docs
  docs/kf.dev/content/en/docs/developers/env/_index.md
  docs/kf.dev/content/en/docs/developers/env/defaults/_index.md
Labels: cla: yes

#529 pkg/kf/internal/tools: title casing for WithXXX
  pkg/kf/apps/zz_generated.client.go
  pkg/kf/apps/zz_generated.clientoptions.go
  pkg/kf/commands/routes/delete_route.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.clientoptions.go
  pkg/kf/internal/tools/clientgen/tmplclient.go
  pkg/kf/internal/tools/generator/gen.go
  pkg/kf/internal/tools/option-builder/option-builder.go
  pkg/kf/routeclaims/zz_generated.client.go
  pkg/kf/routeclaims/zz_generated.clientoptions.go
  pkg/kf/routes/zz_generated.client.go
  pkg/kf/routes/zz_generated.clientoptions.go
  pkg/kf/sources/zz_generated.client.go
  pkg/kf/sources/zz_generated.clientoptions.go
  pkg/kf/spaces/zz_generated.client.go
  pkg/kf/spaces/zz_generated.clientoptions.go
Labels: cla: yes

#534 do not base64 decode vcap services
  pkg/kf/commands/service-bindings/vcap_services.go
  pkg/kf/commands/service-bindings/vcap_services_test.go
Labels: cla: yes

#436 Status message for destroyed pod
  pkg/kf/apps/log_tailer_test.go
  pkg/kf/logs/fake_watcher_test.go
  pkg/kf/logs/mutex_writer.go
  pkg/kf/logs/tailer.go
  pkg/kf/logs/tailer_test.go
Labels: cla: yes

#537 pkg/reconciler/route: recreate deleted VirtualServices
  pkg/reconciler/app/resources/route.go
  pkg/reconciler/base.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/reconciler.go
  pkg/reconciler/route/resources/virtual_service.go
  pkg/reconciler/route/resources/virtual_service_test.go
Labels: cla: yes

#546 pkg/reconciler/app: handle when app is stopped
  pkg/apis/kf/v1alpha1/app_lifecycle.go
  pkg/apis/kf/v1alpha1/app_lifecycle_test.go
  pkg/reconciler/app/reconciler.go
Labels: cla: yes

#548 Feature/completion
  pkg/kf/commands/apps/app.go
  pkg/kf/commands/apps/delete.go
  pkg/kf/commands/apps/env.go
  pkg/kf/commands/apps/logs.go
  pkg/kf/commands/apps/proxy.go
  pkg/kf/commands/apps/restage.go
  pkg/kf/commands/apps/restart.go
  pkg/kf/commands/apps/scale.go
  pkg/kf/commands/apps/set_env.go
  pkg/kf/commands/apps/start.go
  pkg/kf/commands/apps/stop.go
  pkg/kf/commands/apps/unset_env.go
  pkg/kf/commands/builds/logs.go
  pkg/kf/commands/completion/bash.go
  pkg/kf/commands/completion/bash_test.go
  pkg/kf/commands/completion/generic.go
  pkg/kf/commands/completion/generic_test.go
  pkg/kf/commands/completion/names.go
  pkg/kf/commands/completion/names_test.go
  pkg/kf/commands/config/config.go
  pkg/kf/commands/quotas/delete.go
  pkg/kf/commands/quotas/get.go
  pkg/kf/commands/quotas/update.go
  pkg/kf/commands/root.go
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/delete.go
  pkg/kf/commands/spaces/get.go
  pkg/kf/commands/target.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
Labels: cla: yes

#522 pkg/kf/commands/install/kf: add retry logic for kf
  pkg/kf/commands/install/kf/kf.go
Labels: cla: yes

#558 docs: correct service binding lifecycle in Spring Music
  docs/kf.dev/content/en/docs/getting-started/spring-music/_index.md
Labels: cla: yes

#565 cmd/webhook: changes webhook name to webhook.kf.dev
  cmd/webhook/main.go
Labels: cla: yes

#567 pkg/kf/kf/istio: moved istio client to own package
  pkg/kf/commands/apps/proxy.go
  pkg/kf/commands/apps/proxy_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/doc.go
  pkg/kf/istio/fake/fake_istio_client.go
  pkg/kf/istio/fake/interfaces.go
  pkg/kf/istio/istio_client.go
  pkg/kf/istio/istio_client_options.go
  pkg/kf/istio/istio_client_options.yml
  pkg/kf/istio/istio_client_test.go
Labels: cla: yes

#559 Fix options test in CLI help output. Fixes #211
  pkg/kf/commands/group/group.go
  pkg/kf/commands/group/group_test.go
  pkg/kf/commands/root.go
Labels: cla: yes

#564 pkg/kf/commands/install: refactor to use ExponetialBackoff
  pkg/kf/commands/install/go.mod
  pkg/kf/commands/install/go.sum
  pkg/kf/commands/install/kf/kf.go
Labels: cla: yes

#571 docs: Document "Customizing Buildpacks"
  docs/kf.dev/content/en/docs/operators/customizing-buildpacks/_index.md
Labels: cla: yes

#570 pkg/kf/commands/install/kf: ensure deployments are ready
  pkg/kf/commands/install/kf/kf.go
Labels: cla: yes

#573 pkg/kf/commands/service-bindings: tip user to restart app
  pkg/kf/commands/service-bindings/bind-service.go
Labels: cla: yes

#525 Supports KUBECONFIG when initKubeConfig
  pkg/kf/commands/config/config.go
  pkg/kf/commands/config/config_test.go
Labels: cla: yes

#586 pkg/kf/commands/services: update views match cf
  go.mod
  go.sum
  pkg/kf/commands/apps/apps.go
  pkg/kf/commands/services/create-service.go
  pkg/kf/commands/services/helpers_test.go
  pkg/kf/commands/services/service.go
  pkg/kf/commands/services/service_test.go
  pkg/kf/commands/services/services.go
  pkg/kf/commands/services/services_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/describe/describe.go
  pkg/kf/describe/describe_test.go
  pkg/kf/services/fake/fake_client_interface.go
  pkg/kf/services/options.go
  pkg/kf/services/options.yml
  pkg/kf/services/services.go
  pkg/kf/services/services_test.go
  pkg/kf/services/utils.go
  pkg/kf/services/utils_test.go
Labels: cla: yes

#587 Fix reconciler logs
  pkg/reconciler/app/controller.go
  pkg/reconciler/app/reconciler.go
  pkg/reconciler/base.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/reconciler.go
  pkg/reconciler/source/controller.go
  pkg/reconciler/source/reconciler.go
  pkg/reconciler/space/controller.go
  pkg/reconciler/space/reconciler.go
Labels: cla: yes

#592 Fix/remove submodule
  go.mod
  go.sum
  pkg/kf/commands/install/go.mod
  pkg/kf/commands/install/go.sum
Labels: cla: yes

#596 added kodata to include info remotely
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/LICENSE
  cmd/controller/kodata/VENDOR-LICENSE
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/LICENSE
  cmd/webhook/kodata/VENDOR-LICENSE
Labels: cla: yes, enhancement

#594 docs: Add troubleshooting page for devs
  docs/kf.dev/content/en/docs/developers/troubleshooting/_index.md
Labels: cla: yes

#600 update kf services output
  pkg/kf/commands/services/helpers_test.go
  pkg/kf/commands/services/services.go
  pkg/kf/commands/services/services_test.go
Labels: cla: yes

#623 Attempt to fix concourse PR pipelines for forks
  ci/concourse/pipelines/kf-pipeline.yml
  ci/concourse/pipelines/pr-pipeline.yml
Labels: cla: yes

#625 Fix ci_git_branch
  ci/concourse/pipelines/pr-pipeline.yml
Labels: cla: yes

#603 pkg/reconciler/route: Change ownership scheme
  cmd/webhook/main.go
  docs/developer-guide/configuring-routes.md
  pkg/apis/kf/v1alpha1/route_defaults.go
  pkg/apis/kf/v1alpha1/route_defaults_test.go
  pkg/apis/kf/v1alpha1/route_validation.go
  pkg/apis/kf/v1alpha1/route_validation_test.go
  pkg/kf/commands/routes/routes.go
  pkg/kf/commands/routes/routes_test.go
  pkg/reconciler/app/controller.go
  pkg/reconciler/app/resources/route.go
  pkg/reconciler/app/resources/route_test.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/controller_test.go
  pkg/reconciler/route/fake_corev1_listers.go
  pkg/reconciler/route/fake_istio_listers.go
  pkg/reconciler/route/fake_kf.go
  pkg/reconciler/route/fake_kf_v1alpha1.go
  pkg/reconciler/route/fake_listers.go
  pkg/reconciler/route/fake_networking.go
  pkg/reconciler/route/fake_reconciler.go
  pkg/reconciler/route/fake_shared_client.go
  pkg/reconciler/route/reconciler.go
  pkg/reconciler/route/reconciler_test.go
  pkg/reconciler/route/resources/virtual_service.go
  pkg/reconciler/route/resources/virtual_service_test.go
Labels: cla: yes

#627 pkg/kf/logs: fix warning message
  pkg/kf/logs/tailer.go
Labels: cla: yes

#628 pkg/kf/commands/install/gke: SilenceUsage for PreRun
  pkg/kf/commands/install/gke/gke.go
Labels: cla: yes

#615 fixes #608
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_bind-service.md
  pkg/kf/apps/client.go
  pkg/kf/apps/client_test.go
  pkg/kf/cfutil/systemenvinjector_test.go
  pkg/kf/cfutil/vcap.go
  pkg/kf/cfutil/vcap_test.go
  pkg/kf/commands/service-bindings/bind-service.go
  pkg/kf/commands/service-bindings/bind-service_test.go
  pkg/kf/commands/service-bindings/integration_test.go
  pkg/kf/service-bindings/client.go
  pkg/kf/service-bindings/fake/fake_client_interface.go
Labels: cla: yes

#631 update concourse-pr-set.sh for fork support
  hack/concourse-pr-set.sh
Labels: cla: yes

#622 pkg/reconciler/app: gc after revision is ready
  pkg/reconciler/app/reconciler.go
Labels: cla: yes

#632 ci: break unit and integration tests out
  ci/concourse/pipelines/pr-pipeline.yml
  hack/integration-test.sh
  pkg/kf/commands/service-bindings/integration_test.go
  pkg/kf/testutil/integration.go
Labels: cla: yes

#643 pkg/kf/commands/apps: use status to report app state
  pkg/kf/commands/apps/apps.go
  pkg/kf/commands/apps/apps_test.go
Labels: cla: yes

#641 fixes #635
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/_index.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_logs.md
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/apps/logs.go
Labels: cf compatibility, cla: yes

#645 made restage return logs
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_restage.md
  pkg/kf/apps/client.go
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/apps/log_tailer.go
  pkg/kf/apps/push.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/restage.go
  pkg/kf/commands/apps/restage_test.go
Labels: bug, cf compatibility, cla: yes
