Repository google/kf, pull requests merged in 2019-10, with the labels that each got.

#716 hack: update-codegen.sh rejects invalid arg
  hack/update-codegen.sh
Labels: cla: yes

#719 change check-code-generator to bash
  hack/check-code-generator.sh
Labels: cla: yes

#722 pkg/kf/commands/install/gke: use default GKE
  pkg/kf/commands/install/gke/gke.go
Labels: cla: yes

#712 changed manifest to produce sub-types
  pkg/kf/apps/kfapp.go
  pkg/kf/apps/kfapp_test.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/manifest/manifest_conversion.go
  pkg/kf/manifest/manifest_conversion_test.go
  pkg/kf/manifest/manifest_validation.go
  pkg/kf/manifest/manifest_validation_test.go
Labels: cla: yes, cleanup

#723 changed apps commands to support async
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_map-route.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_restart.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_scale.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_set-env.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_start.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_stop.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_unmap-route.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_unset-env.md
  pkg/kf/apps/client.yml
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/apps/zz_generated.client.go
  pkg/kf/commands/apps/logs_test.go
  pkg/kf/commands/apps/restart.go
  pkg/kf/commands/apps/restart_test.go
  pkg/kf/commands/apps/scale.go
  pkg/kf/commands/apps/scale_test.go
  pkg/kf/commands/apps/set_env.go
  pkg/kf/commands/apps/set_env_test.go
  pkg/kf/commands/apps/start.go
  pkg/kf/commands/apps/start_test.go
  pkg/kf/commands/apps/stop.go
  pkg/kf/commands/apps/stop_test.go
  pkg/kf/commands/apps/unset_env.go
  pkg/kf/commands/apps/unset_env_test.go
  pkg/kf/commands/routes/map_route.go
  pkg/kf/commands/routes/map_route_test.go
  pkg/kf/commands/routes/unmap_route.go
  pkg/kf/commands/routes/unmap_route_test.go
Labels: cla: yes

#717 Make Service Provision/Deletion sync
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-service.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-service.md
  pkg/kf/apps/zz_generated.client.go
  pkg/kf/commands/services/create-service.go
  pkg/kf/commands/services/create-service_test.go
  pkg/kf/commands/services/delete-service.go
  pkg/kf/commands/services/delete-service_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
  pkg/kf/internal/tools/clientgen/tmplfunctional.go
  pkg/kf/internal/tools/clientgen/tmplheader.go
  pkg/kf/marketplace/client.go
  pkg/kf/marketplace/client_test.go
  pkg/kf/marketplace/fake/fake_client_interface.go
  pkg/kf/services/client.go
  pkg/kf/services/client.yml
  pkg/kf/services/client_test.go
  pkg/kf/services/fake/fake_client.go
  pkg/kf/services/zz_generated.client.go
Labels: cf compatibility, cla: yes

#729 pkg/kf/apps: fix {Unb,B}indService funcs
  pkg/kf/apps/client.go
Labels: cla: yes

#665 Added support for Dockerfile builds via kaniko
  config/300-kaniko-clusterbuildtemplate.yaml
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_push.md
  pkg/apis/kf/v1alpha1/app_masks.go
  pkg/apis/kf/v1alpha1/app_masks_test.go
  pkg/apis/kf/v1alpha1/source_lifecycle.go
  pkg/apis/kf/v1alpha1/source_types.go
  pkg/apis/kf/v1alpha1/source_validation.go
  pkg/apis/kf/v1alpha1/source_validation_test.go
  pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/apps/testdata/dockerfile-app/Dockerfile
  pkg/kf/commands/apps/testdata/manifest.yml
  pkg/kf/describe/describe.go
  pkg/kf/describe/describe_test.go
  pkg/kf/manifest/manifest.go
  pkg/kf/manifest/manifest_test.go
  pkg/kf/sources/kfsource.go
  pkg/reconciler/app/resources/source.go
  pkg/reconciler/app/resources/source_test.go
  pkg/reconciler/source/resources/build.go
  samples/apps/helloworld/Dockerfile
  samples/apps/helloworld/main.go
Labels: cla: yes, enhancement

#733 Add version file
  version
Labels: cla: yes

#740 third_party: Update VENDOR-LICENSE
  third_party/VENDOR-LICENSE
Labels: cla: yes

#732 pkg/kf/commands/apps: support .cfignore files
  go.mod
  go.sum
  pkg/kf/commands/apps/integration_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  samples/apps/cfignore/.cfignore
  samples/apps/cfignore/.gitignore
  samples/apps/cfignore/garbage.o
  samples/apps/cfignore/go.mod
  samples/apps/cfignore/go.sum
  samples/apps/cfignore/main.go
  third_party/VENDOR-LICENSE
Labels: cla: yes

#734 Feature/release automation
  ci/concourse/README.md
  ci/concourse/pipelines/kf-pipeline.yml
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/pr-pipeline.yml
  ci/concourse/pipelines/release-pipeline.yml
  ci/concourse/terraform/.gitignore
  ci/concourse/terraform/main.tf
  config/100-namespace.yaml
  docs/install.md
  docs/kf.dev/content/en/docs/getting-started/install/_index.md
  hack/build-release.sh
  hack/build.sh
  hack/check-go-generate.sh
  hack/check-go-sum.sh
  hack/check-linters.sh
  hack/check-vendor-license.sh
  hack/clean-integration-tests.sh
  hack/concourse-login.sh
  hack/concourse-pr-destroy.sh
  hack/concourse-pr-set.sh
  hack/concourse-set.sh
  hack/generate-command-docs.sh
  hack/integration-test.sh
  hack/ko-apply.sh
  hack/pre-commit.sh
  hack/tail-controller.sh
  hack/test.sh
  hack/unit-test.sh
  hack/update-codegen.sh
  hack/update-vendor-license.sh
  hack/upload-release.sh
  hack/util.sh
  pkg/kf/commands/install/kf/kf.go
  releasing.md
Labels: cla: yes

#741 Fix configure-space set-default-domain
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/config_space_test.go
Labels: cla: yes

#742 Add vcap-services completion
  pkg/kf/commands/service-bindings/vcap_services.go
Labels: cla: yes

#745 Improve release pipeline
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/release-pipeline.yml
Labels: cla: yes

#752 pkg/kf/apps: ensure ServiceBindings are preserved
  pkg/kf/apps/push.go
  pkg/kf/apps/push_test.go
Labels: cla: yes

#753 fixed ko apply
  hack/ko-apply.sh
Labels: bug, cla: yes

#756 fix routes ready status on app
  pkg/apis/kf/v1alpha1/app_lifecycle.go
  pkg/kf/commands/routes/integration_test.go
  pkg/kf/testutil/integration.go
  pkg/reconciler/app/reconciler.go
Labels: cla: yes

#761 Hotfix/serving8 issue
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_install_gke.md
  pkg/apis/kf/v1alpha1/app_defaults.go
  pkg/apis/kf/v1alpha1/app_defaults_test.go
  pkg/kf/commands/install/gke/gke.go
Labels: bug, cla: yes

#773 Merge in master
  CHANGELOG.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_install_gke.md
  pkg/apis/kf/v1alpha1/app_defaults.go
  pkg/apis/kf/v1alpha1/app_defaults_test.go
  pkg/apis/kf/v1alpha1/app_lifecycle.go
  pkg/kf/apps/push.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/install/gke/gke.go
  pkg/kf/commands/routes/integration_test.go
  pkg/kf/testutil/integration.go
  pkg/reconciler/app/reconciler.go
  version
Labels: cla: yes

#748 ci/concourse/pipeline: check step needs more time
  ci/concourse/pipelines/pr-pipeline.yml
Labels: cla: yes

#680 docs: publish site to App Engine
  docs/kf.dev/app.yaml
  docs/kf.dev/ci/concourse/README.md
  docs/kf.dev/ci/concourse/image/Dockerfile
  docs/kf.dev/ci/concourse/pipelines/website-pipeline.yml
  docs/kf.dev/firebase.json
  docs/kf.dev/hack/build-and-deploy.sh
  docs/kf.dev/hack/localpreview.sh
Labels: cla: yes

#771 added support for selecting machine types
  pkg/kf/commands/install/gke/gke.go
  third_party/VENDOR-LICENSE
Labels: cla: yes, enhancement

#776 docs: Publish develop branch as default
  docs/kf.dev/ci/concourse/pipelines/website-pipeline.yml
Labels: cla: yes

#777 ci: Install svcat from the correct source
  ci/concourse/pipelines/release-pipeline.yml
Labels: cla: yes

#760 third_party/knative-build: move Status to v1beta1
  pkg/apis/kf/v1alpha1/source_lifecycle.go
  pkg/apis/kf/v1alpha1/source_lifecycle_test.go
  third_party/knative-build/pkg/apis/build/v1alpha1/build_types.go
  third_party/knative-build/pkg/logs/logs.go
Labels: cla: yes

#746 Add build info step to buildpack pipeline
  cmd/setup-buildpack-build/kodata/HEAD
  cmd/setup-buildpack-build/kodata/LICENSE
  cmd/setup-buildpack-build/kodata/VENDOR-LICENSE
  cmd/setup-buildpack-build/main.go
  config/300-buildpack-clusterbuildtemplate.yaml
  go.mod
  go.sum
  pkg/dockerutil/testdata/credhelpers/config.json
  pkg/dockerutil/testdata/customauth/config.json
  pkg/dockerutil/util.go
  pkg/dockerutil/util_test.go
  pkg/kf/commands/debug.go
  third_party/VENDOR-LICENSE
Labels: cla: yes

#781 ci: Pin Terraform version
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/release-pipeline.yml
  ci/concourse/terraform/main.tf
Labels: cla: yes

#774 Update Google Cloud SDK version in Concourse Image
  ci/concourse/image/Dockerfile
Labels: cla: yes

#784 Add scripts to scrape Cloud Run documentation
  hack/flatten-supported-gke-versions.py
  hack/scrape-supported-gke-versions.py
Labels: cla: yes

#782 add more time to flaky test
  pkg/kf/commands/apps/integration_test.go
Labels: cla: yes

#787 Pin concourse image to go 1.12
  ci/concourse/image/Dockerfile
Labels: cla: yes

#788 Update PR pipeline to use hack/ko-apply.sh
  ci/concourse/pipelines/pr-pipeline.yml
Labels: cla: yes

#790 Fix hack/update-codegen.sh so it takes 1 min
  hack/update-codegen.sh
Labels: cla: yes

#789 Split check step into multiple, aggregate steps
  ci/concourse/pipelines/pr-pipeline.yml
Labels: cla: yes

#778 made spaces synchronous
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-space.md
  pkg/kf/commands/spaces/delete.go
  pkg/kf/commands/spaces/delete_test.go
Labels: cf compatibility, cla: yes

#794 Feature: Single pipeline for PR tests
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/pr-unipipeline.yml
  ci/concourse/terraform/main.tf
Labels: cla: yes, ok-to-test

#798 fix pipeline
  ci/concourse/pipelines/pr-pipeline.yml
Labels: cla: yes

#796 pkg/kf/apps: handle metav1.Status failures in logs
  pkg/kf/apps/log_tailer.go
  pkg/kf/apps/log_tailer_test.go
Labels: cla: yes, ok-to-test

#799 Remove the pr pipeline
  ci/concourse/pipelines/kf-pipeline.yml
  ci/concourse/pipelines/pr-pipeline.yml
Labels: cla: yes

#780 Fixes 430
  pkg/kf/apps/client.go
  pkg/kf/apps/fake/fake_client.go
  pkg/kf/commands/apps/delete.go
  pkg/kf/commands/apps/delete_test.go
  pkg/kf/commands/apps/integration_test.go
Labels: cla: yes

#792 Generate all clients
  go.mod
  go.sum
  hack/pre-commit.sh
  hack/update-codegen.sh
  pkg/client/injection/informers/kubernetes/limitrange/fake/fake.go
  pkg/client/injection/informers/kubernetes/limitrange/limitrange.go
  pkg/client/injection/informers/kubernetes/resourcequota/fake/fake.go
  pkg/client/injection/informers/kubernetes/resourcequota/resourcequota.go
  pkg/reconciler/space/controller.go
  third_party/VENDOR-LICENSE
Labels: cla: yes, ok-to-test

#709 Support multiple apps per route
  pkg/apis/kf/v1alpha1/route_defaults.go
  pkg/kf/commands/routes/integration_test.go
  pkg/kf/testutil/assertions.go
  pkg/reconciler/route/reconciler.go
  pkg/reconciler/route/resources/virtual_service.go
  pkg/reconciler/route/resources/virtual_service_test.go
Labels: cla: yes

#795 pkg/reconciler/space: add build Service Account
  pkg/apis/kf/v1alpha1/space_lifecycle.go
  pkg/apis/kf/v1alpha1/space_lifecycle_test.go
  pkg/reconciler/space/controller.go
  pkg/reconciler/space/reconciler.go
  pkg/reconciler/space/resources/build_service_account.go
  pkg/reconciler/space/resources/build_service_account_test.go
Labels: cla: yes, ok-to-test

#783 Make space an optional arg to configure-space
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_append-domain.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-buildpack-builder.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-buildpack-env.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-container-registry.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-domains.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-execution-env.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_remove-domain.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-buildpack-builder.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-buildpack-env.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-container-registry.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-default-domain.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-env.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_unset-buildpack-env.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_unset-env.md
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/config_space_test.go
Labels: cla: yes

#786 pkg/kf/commands/spaces: configure BuildServiceAccount
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-build-service-account.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-build-service-account.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-space.md
  pkg/kf/commands/spaces/config_space.go
  pkg/kf/commands/spaces/config_space_test.go
  pkg/kf/commands/spaces/create.go
  pkg/kf/commands/spaces/create_test.go
  pkg/kf/commands/spaces/get.go
  pkg/kf/commands/spaces/get_test.go
  pkg/kf/spaces/kfspace.go
  pkg/kf/spaces/kfspace_test.go
Labels: cla: yes, ok-to-test

#801 pkg/kf/logs: refactor tailer_test.go
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-build-service-account.md
  docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-build-service-account.md
  pkg/kf/commands/wire_gen.go
  pkg/kf/commands/wire_injector.go
  pkg/kf/logs/fake_watcher_test.go
  pkg/kf/logs/mutex_writer.go
  pkg/kf/logs/options.go
  pkg/kf/logs/options.yml
  pkg/kf/logs/tailer.go
  pkg/kf/logs/tailer_test.go
Labels: cla: yes, ok-to-test

#808 pkg/reconciler/app: fix TODO comment
  pkg/reconciler/app/reconciler.go
Labels: cla: yes

#815 pkg/reconciler: log reconcile diffs
  pkg/reconciler/app/reconciler.go
  pkg/reconciler/route/reconciler.go
  pkg/reconciler/space/reconciler.go
Labels: cla: yes

#819 ci: add unified PR pipeline
  ci/concourse/pipelines/pr-unipipeline.yml
Labels: cla: yes

#813 pkg/reconciler/space: don't reconcile ServiceAccounts secrets
  pkg/reconciler/space/reconciler.go
Labels: cla: yes, ok-to-test

#810 pkg/apis/kf/v1alpha1: update service defaults
  pkg/apis/kf/v1alpha1/app_defaults.go
  pkg/apis/kf/v1alpha1/app_defaults_test.go
  pkg/kf/apps/health_check.go
  pkg/kf/apps/health_check_test.go
  pkg/kf/commands/apps/push_test.go
Labels: cla: yes, ok-to-test

#820 pkg/reconciler/source: move Build to use Secrets
  pkg/apis/kf/v1alpha1/source_lifecycle.go
  pkg/apis/kf/v1alpha1/source_lifecycle_test.go
  pkg/reconciler/app/controller.go
  pkg/reconciler/app/reconciler.go
  pkg/reconciler/base.go
  pkg/reconciler/source/controller.go
  pkg/reconciler/source/reconciler.go
  pkg/reconciler/source/resources/build.go
  pkg/reconciler/source/resources/build_test.go
Labels: cla: yes, ok-to-test

#829 pkg/reconciler/source: fix Secret Status
  pkg/apis/kf/v1alpha1/source_lifecycle_test.go
  pkg/reconciler/source/reconciler.go
Labels: cla: yes

#826 bumped GKE versions
  ci/concourse/pipelines/nightly-release-pipeline.yml
  ci/concourse/pipelines/pr-unipipeline.yml
  ci/concourse/pipelines/release-pipeline.yml
  pkg/kf/commands/install/gke/gke.go
Labels: cla: yes

#830 pkg/kf/commands/install/gke: fix cluster zlone selection
  pkg/kf/commands/install/gke/gke.go
Labels: cla: yes

#832 Update gateway names and namespaces
  pkg/kf/istio/istio_client_options.go
  pkg/kf/istio/istio_client_options.yml
  pkg/kf/istio/istio_client_test.go
  pkg/reconciler/route/resources/virtual_service.go
  pkg/reconciler/route/resources/virtual_service_test.go
Labels: cla: yes, ok-to-test

#828 fixes intermittent push failures
  pkg/apis/kf/v1alpha1/utils.go
  pkg/apis/kf/v1alpha1/utils_test.go
  pkg/kf/apps/log_tailer.go
Labels: bug, cla: yes, ok-to-test

#831 Ask user for public/internal GKE server IP
  pkg/kf/commands/install/gke/gke.go
Labels: cla: yes

#728 move push to taking a container
  pkg/kf/apps/health_check.go
  pkg/kf/apps/health_check_test.go
  pkg/kf/apps/kfapp.go
  pkg/kf/apps/kfapp_test.go
  pkg/kf/apps/log_tailer.go
  pkg/kf/apps/push-options.yml
  pkg/kf/apps/push.go
  pkg/kf/apps/push_options.go
  pkg/kf/apps/push_test.go
  pkg/kf/commands/apps/push.go
  pkg/kf/commands/apps/push_test.go
  pkg/kf/manifest/manifest_conversion.go
  pkg/kf/manifest/manifest_conversion_test.go
Labels: cla: yes, ok-to-test
